In [112]:
import re
import json
import pandas as pd
import numpy as np
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LassoCV
from sklearn.linear_model import Lasso
from linearmodels.panel import PanelOLS
from linearmodels.iv import IV2SLS
from sklearn.model_selection import KFold
from pathlib import Path

In [113]:
# Generalised demeaning helper function
def demean_2FE(df):
    # Copying dataframe
    df_fe = df.copy()
    # Looping over all columns
    for col in df.columns:
        # Grouping by FE type and and create mean vector
        e_mean = df_fe[col].groupby(level='entity_id').transform('mean')
        t_mean = df_fe[col].groupby(level='year').transform('mean')
        total_mean = df_fe[col].mean()
        # Demeaning
        df_fe[col] = df_fe[col] - e_mean - t_mean + total_mean
    return df_fe

In [114]:
IN = Path("data/processed")

final = json.loads((IN / "final.json").read_text())
df = pd.read_parquet(IN / "bfs_data.parquet")

y = final["endog"]
Z = final["Z_selected"]

# Rebuilding multi-index
dfp = df.set_index([final["entity_level"], final["time_level"]]).sort_index()

# Demeaning using helper function
df_dm = demean_2FE(dfp[[y] + Z].dropna())
# Outcome vector
y_dm = df_dm[y]
# Regressor matrix
X_dm = df_dm[Z]

In [115]:
dfp

                log_area_lead1  log_yield  Z_temp_m2  Z_temp_m4  Z_temp_m5  \
entity_id year
AL_WHEAT  1961       10.463103   3.258097   2.209975  -2.204850  -1.669153
          1962       10.645425   3.178054   4.148131  -1.569209   2.647645
          1963       11.066638   3.157000  -3.557254   1.536983   0.547841
          1964       10.915088   3.218876  -2.979757   1.341887   0.335248
          1965       10.985293   3.198673  -0.986176   1.744010   1.152825
...                        ...        ...        ...        ...        ...
WY_WHEAT  2020       11.461632   3.258097  -1.979939  -1.622294   0.536157
          2021       11.461632   3.465736  -3.622384  -1.431581  -0.305844
          2022       11.407565   2.833213  -1.815428  -2.538534  -1.389492
          2023       11.418615   3.401197  -2.957430  -2.322875   2.016526
          2024       11.396392   3.433987   2.365781   0.721691  -1.671981

                Z_temp_m6  Z_temp_m7  Z_temp_m8  Z_prcp_m1  Z_prcp_m5  \
entity_id year
AL_WHEAT  1961  -2.050904  -1.099310  -1.154869 -45.915553 -36.864447
          1962  -0.348043   0.381419   0.310272  57.177780 -78.811113
          1963  -0.287447  -1.151925  -0.282538  37.277780 -19.657780
          1964   0.651534  -0.891265  -0.738219  24.624447 -35.458732
          1965  -0.953697  -0.711931  -0.597013 -24.110315 -82.873018
...                   ...        ...        ...        ...        ...
WY_WHEAT  2020   0.259534  -0.031980   2.064114   0.404550 -23.989882
          2021   3.481911   2.343117   0.043374  -6.053892 -11.491265
          2022   0.031471   1.612886   1.850630  -3.325320   8.862292
          2023  -0.591113  -0.133623   0.024153   8.952656 -17.437708
          2024   1.896849   0.533008   0.839526  -3.354541  -4.968538

                Z_prcp_m6  Z_prcp_m8  Z_prcp_m11  Z_prcp_m12  Z_temp_m3  \
entity_id year
AL_WHEAT  1961  65.777775  16.767785   24.515399  171.686542   1.202609
          1962  21.004442 -48.672215   10.748732  -51.873458  -2.478109
          1963  20.011108 -44.438882    7.828732   -1.071554   1.668145
          1964 -40.824130   3.532913    7.195399    8.653208  -1.102255
          1965  60.268727   5.387309  -45.360315  -40.900125  -2.304392
...                   ...        ...         ...         ...        ...
WY_WHEAT  2020  -6.349700 -20.063375   -3.625192   -3.240791   1.126642
          2021 -27.654246  13.848147   -9.902832    3.015919   0.578136
          2022 -14.049108  11.761190    2.452784    4.194328   0.606420
          2023  54.642197  24.661190   -1.881093   -9.110563  -4.430004
          2024 -28.088445   4.134482   -5.589788   -6.224990   0.704592

                Z_prcp_m7  Z_prcp_m3
entity_id year
AL_WHEAT  1961 -17.691224  63.721351
          1962 -33.204557 -13.765316
          1963  12.102109 -20.485316
          1964  58.823776  43.905160
          1965  21.824967  20.190875
...                   ...        ...
WY_WHEAT  2020 -17.377663  -2.974686
          2021  -9.154540  -4.864541
          2022 -14.489323 -10.931207
          2023  -1.920844  -2.618164
          2024 -13.445844   5.623338

[2631 rows x 17 columns]

# Scaling for LASSO

In [116]:
scaler = StandardScaler(with_mean=True, with_std=True)

X_std = scaler.fit_transform(X_dm.values)
dfX_std = pd.DataFrame(X_std, index=X_dm.index, columns=X_dm.columns)

# Checking if standardization worked (mean=0, std=1)
print(dfX_std.describe().loc[["mean","std"]].round().head())

      Z_temp_m2  Z_temp_m4  Z_temp_m5  Z_temp_m6  Z_temp_m7  Z_temp_m8  \
mean       -0.0       -0.0        0.0       -0.0        0.0       -0.0
std         1.0        1.0        1.0        1.0        1.0        1.0

      Z_prcp_m1  Z_prcp_m5  Z_prcp_m6  Z_prcp_m8  Z_prcp_m11  Z_prcp_m12  \
mean       -0.0        0.0        0.0        0.0         0.0        -0.0
std         1.0        1.0        1.0        1.0         1.0         1.0

      Z_temp_m3  Z_prcp_m7  Z_prcp_m3
mean       -0.0        0.0        0.0
std         1.0        1.0        1.0

# BFS Rule
Depth 0: Default Z
Depth 1: Simple non-linearities

Non-linearity candidates

Squares x^2

Cubics: x^3

Abs: |x|

Hinge splines: max(0, x-c), max(0, c-x)

In [117]:
X_nonlinear = dfX_std.copy()

quantiles = [0.25, 0.5, 0.75]

cols = X_nonlinear.columns
print(len(cols))
for col in cols:
    # Polynomials
    X_nonlinear[f'{col}__sq'] = X_nonlinear[col] ** 2
    X_nonlinear[f'{col}__cu'] = X_nonlinear[col] ** 3
    # Absolute value
    X_nonlinear[f"{col}__abs"] = X_nonlinear[col].abs()

new_cols = {}

for col in cols:
    x = X_nonlinear[col]
    # Iterating over quantiles
    for q in quantiles:
        # Cutting at quantile q
        c = x.quantile(q)
        new_cols[f"{col}__hinge_pos_q{int(q*100)}"] = (x - c).clip(lower=0)
        new_cols[f"{col}__hinge_neg_q{int(q*100)}"] = (c - x).clip(lower=0)

X_nonlinear = pd.concat([X_nonlinear, pd.DataFrame(new_cols, index=X_nonlinear.index)], axis=1)

print(len(X_nonlinear.columns))
print(X_nonlinear.columns)

15
150
Index(['Z_temp_m2', 'Z_temp_m4', 'Z_temp_m5', 'Z_temp_m6', 'Z_temp_m7',
       'Z_temp_m8', 'Z_prcp_m1', 'Z_prcp_m5', 'Z_prcp_m6', 'Z_prcp_m8',
       ...
       'Z_prcp_m7__hinge_pos_q50', 'Z_prcp_m7__hinge_neg_q50',
       'Z_prcp_m7__hinge_pos_q75', 'Z_prcp_m7__hinge_neg_q75',
       'Z_prcp_m3__hinge_pos_q25', 'Z_prcp_m3__hinge_neg_q25',
       'Z_prcp_m3__hinge_pos_q50', 'Z_prcp_m3__hinge_neg_q50',
       'Z_prcp_m3__hinge_pos_q75', 'Z_prcp_m3__hinge_neg_q75'],
      dtype='object', length=150)

# Running LASSO CV

In [118]:
X_vals = X_nonlinear.values
y_vals = y_dm.values

lasso_cv = LassoCV(
    cv=5,
    alphas=100,
    max_iter=20000,
    random_state=0
)

lasso_cv.fit(X_vals, y_vals)

print("Chosen alpha:", lasso_cv.alpha_)
print("Nonzero coefs:", np.sum(lasso_cv.coef_ != 0))

Chosen alpha: 0.00041303547172534305
Nonzero coefs: 60

# Next Step is stability (test over subsamples)

In [119]:
X_all = X_nonlinear.values
y_all = y_dm.values
feature_names = X_nonlinear.columns.to_numpy()

# Extracting alpha chosen by LassoCV
alpha = float(lasso_cv.alpha_)

# Resampling entities
entities = X_nonlinear.index.get_level_values("entity_id").to_numpy()
unique_entities = np.unique(entities)

# No. sample runs
B = 200
# Fraction of entities per run
frac = 0.7
# Seeding
rng = np.random.default_rng(0)

sel_counts = np.zeros(X_all.shape[1], dtype=int)
coef_sums = np.zeros(X_all.shape[1], dtype=float)

for b in range(B):
    # sample entities with replacement, then keep all their rows
    m = int(np.ceil(frac * len(unique_entities)))
    sampled_ents = rng.choice(unique_entities, size=m, replace=True)

    mask = np.isin(entities, sampled_ents)
    X_b = X_all[mask]
    y_b = y_all[mask]

    # Fitting LASSO at fixed alpha
    model = Lasso(alpha=alpha, max_iter=20000, random_state=0)
    model.fit(X_b, y_b)

    nz = model.coef_ != 0
    sel_counts[nz] += 1
    coef_sums[nz] += model.coef_[nz]

# Selection frequencies + mean coef conditional on selection
sel_freq = sel_counts / B
mean_coef = np.zeros_like(coef_sums)
nonzero_mask = sel_counts > 0
mean_coef[nonzero_mask] = coef_sums[nonzero_mask] / sel_counts[nonzero_mask]

stable_cand = (
    pd.DataFrame(
        {
            "feature": feature_names,
            "sel_freq": sel_freq,
            "mean_coef_if_selected": mean_coef,
        }
    )
    .sort_values(["sel_freq", "feature"], ascending=[False, True])
    .reset_index(drop=True)
)

stable_cand.head()

                    feature  sel_freq  mean_coef_if_selected
0             Z_prcp_m5__cu     1.000              -0.002926
1             Z_prcp_m8__cu     1.000              -0.000676
2             Z_temp_m2__cu     1.000              -0.002037
3  Z_prcp_m7__hinge_neg_q75     0.995              -0.020635
4             Z_temp_m4__cu     0.995              -0.002114

# Deciding threshold for stable set

In [120]:
# Descriptive stats of candidate set
stable_cand.describe()

# Choosing median 0.7
THRESH = 0.7

# Filtering
stable_cand = stable_cand[stable_cand["sel_freq"] > THRESH]

print(stable_cand.shape)

(42, 3)

# Pruning stable set

In [121]:
def feat_name(feat):
    return feat.split("__")[0]

def feat_transformation(feat):
    if '__hinge' in feat: return "hinge"
    if feat.endswith('__cu'): return "cubic"
    if feat.endswith('__abs'): return "abs"
    if feat.endswith('__sq'): return 'square'
    return 'linear'

def hinge_quartile_search(feat):
    search = re.search(r'q(\d+)', feat)
    return int(search.group(1)) if search else None

stable = stable_cand.copy()
stable['feat_name'] = stable['feature'].apply(feat_name)
stable['feat_trans'] = stable['feature'].apply(feat_transformation)
stable['hinge_q'] = stable['feature'].apply(hinge_quartile_search)

In [122]:
# Imposing stricter threshold
pooled = stable[stable["sel_freq"] >= 0.90].copy()

# Grouping by feature name
grouped = pooled.groupby('feat_name')

chosen_vars = []

for name, group in grouped:
    group = group.sort_values('sel_freq', ascending=False)

    # Hinge takes priority
    hinges = group[group['feat_trans'] == "hinge"]
    # Checking if hinges exist
    if len(hinges):
        # Choosing the best hinge
        chosen_vars.append(hinges.iloc[0]['feature'])
        continue

    # Otherwise check for other transformations and prefer linear/sq
    cand = group[group['feat_trans'].isin(['linear','square', 'cubic'])].copy()
    if len(cand):
        chosen = []
        for f in cand['feature']:
            # If 2 were chosen break the loop
            if len(chosen) >= 2: break
            # Avoid selecting both square and cubic
            if f.endswith('__cu') and any(x.endswith('__sq') for x in chosen):
                continue
            chosen.append(f)
        chosen_vars += chosen

Z_new = chosen_vars
print(Z_new, len(Z_new))

['Z_prcp_m1__hinge_neg_q25', 'Z_prcp_m11__cu', 'Z_prcp_m12__hinge_pos_q25', 'Z_prcp_m3__cu', 'Z_prcp_m5__cu', 'Z_prcp_m5__sq', 'Z_prcp_m6__cu', 'Z_prcp_m6__sq', 'Z_prcp_m7__hinge_neg_q75', 'Z_prcp_m8__cu', 'Z_prcp_m8__sq', 'Z_temp_m2__cu', 'Z_temp_m3__cu', 'Z_temp_m4__cu', 'Z_temp_m5__cu', 'Z_temp_m6__cu', 'Z_temp_m6__sq', 'Z_temp_m7__cu', 'Z_temp_m7__sq', 'Z_temp_m8__cu'] 20

# Running FE on pruned set

In [123]:
# Creating new df with transformations
X = X_nonlinear.reset_index().copy()
y = df['log_yield'].copy()

# Assert y and X have same index length to concatenate
assert X.index.equals(y.index)

# Concatenating dfs
df_fe = pd.concat([X, y], axis=1)

y = "log_yield"
Z = Z_new

df_fe = df_fe.set_index(["entity_id","year"]).sort_index()
df_fe = df_fe[[y] + Z].dropna()

model = PanelOLS(df_fe[y],
                 df_fe[Z],
                 entity_effects=True,
                 time_effects=True).fit(cov_type='clustered', cluster_entity=True)

print(model.summary)

# joint test that all Z coefficients are zero
formula = [f"{z} = 0" for z in Z]
wald = model.wald_test(formula=formula)
print(wald)

                          PanelOLS Estimation Summary
================================================================================
Dep. Variable:              log_yield   R-squared:                        0.0680
Estimator:                   PanelOLS   R-squared (Between):             -0.0094
No. Observations:                2631   R-squared (Within):               0.0158
Date:                Mon, Jan 19 2026   R-squared (Overall):             -0.0093
Time:                        13:57:40   Log-likelihood                    1243.7
Cov. Estimator:             Clustered
                                        F-statistic:                      9.1464
Entities:                          42   P-value                           0.0000
Avg Obs:                       62.643   Distribution:                 F(20,2506)
Min Obs:                       50.000
Max Obs:                       64.000   F-statistic (robust):             15.768
                                        P-value                           0.0000
Time periods:                      64   Distribution:                 F(20,2506)
Avg Obs:                       41.109
Min Obs:                       35.000
Max Obs:                       42.000

                                     Parameter Estimates
=============================================================================================
                           Parameter  Std. Err.     T-stat    P-value    Lower CI    Upper CI
---------------------------------------------------------------------------------------------
Z_prcp_m1__hinge_neg_q25      0.0240     0.0120     2.0041     0.0452      0.0005      0.0475
Z_prcp_m11__cu               -0.0002     0.0005    -0.3029     0.7620     -0.0012      0.0008
Z_prcp_m12__hinge_pos_q25    -0.0112     0.0026    -4.2499     0.0000     -0.0163     -0.0060
Z_prcp_m3__cu                -0.0002     0.0003    -0.7078     0.4791     -0.0008      0.0004
Z_prcp_m5__cu                -0.0029     0.0008    -3.7493     0.0002     -0.0044     -0.0014
Z_prcp_m5__sq                 0.0037     0.0026     1.4455     0.1484     -0.0013      0.0088
Z_prcp_m6__cu                -0.0003     0.0006    -0.6005     0.5482     -0.0015      0.0008
Z_prcp_m6__sq                 0.0019     0.0024     0.7737     0.4392     -0.0029      0.0066
Z_prcp_m7__hinge_neg_q75     -0.0091     0.0050    -1.8438     0.0653     -0.0189      0.0006
Z_prcp_m8__cu                -0.0004     0.0003    -1.0510     0.2934     -0.0011      0.0003
Z_prcp_m8__sq                 0.0027     0.0022     1.2680     0.2049     -0.0015      0.0070
Z_temp_m2__cu                 0.0002     0.0004     0.4938     0.6215     -0.0006      0.0009
Z_temp_m3__cu                 0.0012     0.0007     1.7746     0.0761     -0.0001      0.0025
Z_temp_m4__cu                -0.0008     0.0012    -0.6471     0.5176     -0.0031      0.0016
Z_temp_m5__cu                -0.0017     0.0005    -3.4748     0.0005     -0.0026     -0.0007
Z_temp_m6__cu                -0.0041     0.0006    -6.7588     0.0000     -0.0052     -0.0029
Z_temp_m6__sq                -0.0045     0.0019    -2.2900     0.0221     -0.0083     -0.0006
Z_temp_m7__cu                -0.0030     0.0006    -4.9521     0.0000     -0.0041     -0.0018
Z_temp_m7__sq                -0.0061     0.0033    -1.8817     0.0600     -0.0125      0.0003
Z_temp_m8__cu                -0.0018     0.0008    -2.3533     0.0187     -0.0034     -0.0003
=============================================================================================

F-test for Poolability: 131.37
P-value: 0.0000
Distribution: F(104,2506)

Included effects: Entity, Time
Linear Equality Hypothesis Test
H0: Linear equality constraint is valid
Statistic: 315.3657
P-value: 0.0000
Distributed: chi2(20)

# Interpretation

H0: Linear equality constraint is valid
Statistic: 585.9587
P-value: 0.0000
Distributed: chi2(25)

Storngly reject null that instruments dont have jointly significant explantory power

In [124]:
# Saving list of instruments
Z_final = Z

X_nl = X_nonlinear.copy()
# Making sure nonliner and panel indexes align
assert X_nl.index.equals(dfp.index)


# Creating IV dataframe
df_iv = pd.concat(
    [
        dfp,
        X_nl[Z_final],
    ],
    axis=1,
).reset_index()

# Dropping duplicate cols
df_iv = df_iv.loc[:, ~df_iv.columns.duplicated()].copy()

# 2SLS

In [125]:
Z = Z_final
endog = 'log_yield'
y = "log_area_lead1"

cols_needed = [y, endog] + Z

df_temp = df_iv.dropna(subset=cols_needed)

formula = f"{y} ~ 1 + [{endog} ~ {' + '.join(Z)}] + C(entity_id) + C(year)"

iv_res = IV2SLS.from_formula(
    formula,
    data=df_temp
).fit(cov_type="clustered", clusters=df_temp["entity_id"])

print(iv_res.summary)

                          IV-2SLS Estimation Summary
==============================================================================
Dep. Variable:         log_area_lead1   R-squared:                      0.9453
Estimator:                    IV-2SLS   Adj. R-squared:                 0.9430
No. Observations:                2631   F-statistic:                 1.413e+20
Date:                Mon, Jan 19 2026   P-value (F-stat)                0.0000
Time:                        13:57:41   Distribution:                chi2(105)
Cov. Estimator:             clustered

                                    Parameter Estimates
============================================================================================
                          Parameter  Std. Err.     T-stat    P-value    Lower CI    Upper CI
--------------------------------------------------------------------------------------------
Intercept                    10.974     0.4731     23.195     0.0000      10.046      11.901
C(entity_id)[T.AR_WHEAT]     1.3125     0.0080     164.69     0.0000      1.2969      1.3282
C(entity_id)[T.AZ_WHEAT]    -0.3141     0.1026    -3.0621     0.0022     -0.5152     -0.1131
C(entity_id)[T.CA_WHEAT]     1.2064     0.0702     17.188     0.0000      1.0689      1.3440
C(entity_id)[T.CO_WHEAT]     3.0018     0.0432     69.486     0.0000      2.9171      3.0864
C(entity_id)[T.DE_WHEAT]    -1.1229     0.0329    -34.082     0.0000     -1.1875     -1.0583
C(entity_id)[T.FL_WHEAT]    -1.7758     0.0221    -80.496     0.0000     -1.8191     -1.7326
C(entity_id)[T.GA_WHEAT]     0.5030     0.0031     163.79     0.0000      0.4970      0.5091
C(entity_id)[T.IA_WHEAT]    -1.2073     0.0103    -117.27     0.0000     -1.2275     -1.1871
C(entity_id)[T.ID_WHEAT]     2.2945     0.0671     34.214     0.0000      2.1630      2.4259
C(entity_id)[T.IL_WHEAT]     2.1324     0.0346     61.629     0.0000      2.0646      2.2002
C(entity_id)[T.IN_WHEAT]     1.5856     0.0409     38.735     0.0000      1.5054      1.6658
C(entity_id)[T.KS_WHEAT]     4.4115     0.0210     210.19     0.0000      4.3704      4.4526
C(entity_id)[T.KY_WHEAT]     1.0139     0.0256     39.657     0.0000      0.9638      1.0640
C(entity_id)[T.LA_WHEAT]    -0.2764     0.0147    -18.831     0.0000     -0.3052     -0.2477
C(entity_id)[T.MD_WHEAT]     0.2741     0.0320     8.5770     0.0000      0.2115      0.3367
C(entity_id)[T.MI_WHEAT]     1.6202     0.0427     37.981     0.0000      1.5366      1.7038
C(entity_id)[T.MN_WHEAT]     2.7087     0.0039     696.58     0.0000      2.7011      2.7163
C(entity_id)[T.MO_WHEAT]     2.1087     0.0133     158.26     0.0000      2.0826      2.1348
C(entity_id)[T.MS_WHEAT]     0.2626     0.0026     100.91     0.0000      0.2575      0.2677
C(entity_id)[T.MT_WHEAT]     3.7723     0.0450     83.871     0.0000      3.6842      3.8605
C(entity_id)[T.NC_WHEAT]     1.2060     0.0072     167.92     0.0000      1.1919      1.2200
C(entity_id)[T.ND_WHEAT]     4.2992     0.0305     140.99     0.0000      4.2394      4.3590
C(entity_id)[T.NE_WHEAT]     2.7909     0.0119     235.31     0.0000      2.7676      2.8141
C(entity_id)[T.NJ_WHEAT]    -1.3552     0.0222    -60.941     0.0000     -1.3988     -1.3116
C(entity_id)[T.NM_WHEAT]     0.6526     0.0641     10.184     0.0000      0.5270      0.7782
C(entity_id)[T.NV_WHEAT]    -2.2363     0.0897    -24.921     0.0000     -2.4122     -2.0605
C(entity_id)[T.NY_WHEAT]     0.0588     0.0334     1.7626     0.0780     -0.0066      0.1242
C(entity_id)[T.OH_WHEAT]     2.0421     0.0414     49.328     0.0000      1.9609      2.1232
C(entity_id)[T.OK_WHEAT]     3.6634     0.0490     74.758     0.0000      3.5673      3.7594
C(entity_id)[T.OR_WHEAT]     2.0210     0.0354     57.154     0.0000      1.9517      2.0903
C(entity_id)[T.PA_WHEAT]     0.5781     0.0212     27.320     0.0000      0.5366      0.6195
C(entity_id)[T.SC_WHEAT]     0.2867     0.0076     37.540     0.0000      0.2717      0.3016
C(entity_id)[T.SD_WHEAT]     3.1053     0.0375     82.716     0.0000      3.0317      3.1789
C(entity_id)[T.TN_WHEAT]     0.9245     0.0130     71.053     0.0000      0.8990      0.9500
C(entity_id)[T.TX_WHEAT]     3.3330     0.0554     60.201     0.0000      3.2245      3.4415
C(entity_id)[T.UT_WHEAT]     0.3999     0.0083     48.053     0.0000      0.3836      0.4162
C(entity_id)[T.VA_WHEAT]     0.5170     0.0251     20.634     0.0000      0.4679      0.5661
C(entity_id)[T.WA_WHEAT]     3.0015     0.0377     79.709     0.0000      2.9277      3.0754
C(entity_id)[T.WI_WHEAT]     0.0291     0.0335     0.8682     0.3853     -0.0366      0.0948
C(entity_id)[T.WV_WHEAT]    -2.6345     0.0190    -138.84     0.0000     -2.6717     -2.5973
C(entity_id)[T.WY_WHEAT]     0.5168     0.0552     9.3594     0.0000      0.4086      0.6250
C(year)[T.1962]              0.1102     0.0175     6.2794     0.0000      0.0758      0.1446
C(year)[T.1963]              0.2230     0.0504     4.4275     0.0000      0.1243      0.3218
C(year)[T.1964]              0.0981     0.0568     1.7265     0.0843     -0.0133      0.2094
C(year)[T.1965]              0.0930     0.0599     1.5526     0.1205     -0.0244      0.2103
C(year)[T.1966]              0.3894     0.0810     4.8041     0.0000      0.2305      0.5482
C(year)[T.1967]              0.3054     0.0825     3.7014     0.0002      0.1437      0.4671
C(year)[T.1968]              0.0534     0.0662     0.8060     0.4203     -0.0764      0.1831
C(year)[T.1969]              0.0360     0.0830     0.4337     0.6645     -0.1267      0.1987
C(year)[T.1970]              0.1206     0.0981     1.2287     0.2192     -0.0718      0.3129
C(year)[T.1971]              0.1272     0.1014     1.2536     0.2100     -0.0717      0.3260
C(year)[T.1972]              0.1295     0.0936     1.3838     0.1664     -0.0539      0.3130
C(year)[T.1973]              0.4229     0.0884     4.7820     0.0000      0.2496      0.5962
C(year)[T.1974]              0.4948     0.0928     5.3339     0.0000      0.3130      0.6767
C(year)[T.1975]              0.4927     0.1025     4.8078     0.0000      0.2918      0.6935
C(year)[T.1976]              0.3775     0.0916     4.1218     0.0000      0.1980      0.5570
C(year)[T.1977]              0.0872     0.1015     0.8588     0.3905     -0.1118      0.2861
C(year)[T.1978]              0.3593     0.0954     3.7676     0.0002      0.1724      0.5462
C(year)[T.1979]              0.6085     0.1192     5.1039     0.0000      0.3748      0.8422
C(year)[T.1980]              0.8455     0.1451     5.8275     0.0000      0.5611      1.1299
C(year)[T.1981]              0.8051     0.1604     5.0181     0.0000      0.4906      1.1196
C(year)[T.1982]              0.6028     0.1479     4.0753     0.0000      0.3129      0.8927
C(year)[T.1983]              0.6757     0.1454     4.6463     0.0000      0.3906      0.9607
C(year)[T.1984]              0.5443     0.1387     3.9248     0.0001      0.2725      0.8161
C(year)[T.1985]              0.4561     0.1273     3.5840     0.0003      0.2067      0.7056
C(year)[T.1986]              0.3582     0.1297     2.7617     0.0057      0.1040      0.6124
C(year)[T.1987]              0.4100     0.1411     2.9049     0.0037      0.1334      0.6865
C(year)[T.1988]              0.5784     0.1420     4.0729     0.0000      0.3000      0.8567
C(year)[T.1989]              0.6163     0.1379     4.4707     0.0000      0.3461      0.8865
C(year)[T.1990]              0.3438     0.1363     2.5224     0.0117      0.0767      0.6109
C(year)[T.1991]              0.3745     0.1295     2.8919     0.0038      0.1207      0.6284
C(year)[T.1992]              0.3430     0.1408     2.4357     0.0149      0.0670      0.6190
C(year)[T.1993]              0.3369     0.1431     2.3539     0.0186      0.0564      0.6174
C(year)[T.1994]              0.3239     0.1424     2.2749     0.0229      0.0448      0.6029
C(year)[T.1995]              0.4069     0.1428     2.8489     0.0044      0.1270      0.6868
C(year)[T.1996]              0.3734     0.1317     2.8365     0.0046      0.1154      0.6315
C(year)[T.1997]              0.3304     0.1422     2.3237     0.0201      0.0517      0.6090
C(year)[T.1998]              0.2470     0.1396     1.7694     0.0768     -0.0266      0.5207
C(year)[T.1999]              0.2227     0.1491     1.4936     0.1353     -0.0695      0.5150
C(year)[T.2000]              0.0927     0.1700     0.5451     0.5857     -0.2406      0.4260
C(year)[T.2001]              0.0399     0.1622     0.2457     0.8059     -0.2781      0.3578
C(year)[T.2002]              0.1454     0.1378     1.0555     0.2912     -0.1246      0.4155
C(year)[T.2003]              0.1284     0.1434     0.8951     0.3707     -0.1527      0.4095
C(year)[T.2004]             -0.0462     0.1388    -0.3325     0.7395     -0.3182      0.2259
C(year)[T.2005]             -0.0687     0.1414    -0.4856     0.6272     -0.3458      0.2085
C(year)[T.2006]              0.1483     0.1551     0.9566     0.3388     -0.1556      0.4522
C(year)[T.2007]              0.4079     0.1637     2.4924     0.0127      0.0871      0.7287
C(year)[T.2008]              0.1283     0.1567     0.8187     0.4130     -0.1788      0.4354
C(year)[T.2009]             -0.1588     0.1570    -1.0117     0.3117     -0.4665      0.1489
C(year)[T.2010]              0.1283     0.1640     0.7823     0.4341     -0.1932      0.4499
C(year)[T.2011]              0.1017     0.1703     0.5971     0.5504     -0.2320      0.4353
C(year)[T.2012]              0.2123     0.1733     1.2247     0.2207     -0.1274      0.5520
C(year)[T.2013]              0.0696     0.1732     0.4018     0.6878     -0.2698      0.4090
C(year)[T.2014]              0.0113     0.1713     0.0659     0.9475     -0.3245      0.3471
C(year)[T.2015]             -0.1432     0.1614    -0.8874     0.3748     -0.4595      0.1731
C(year)[T.2016]             -0.3228     0.1641    -1.9670     0.0492     -0.6445     -0.0012
C(year)[T.2017]             -0.3619     0.1737    -2.0833     0.0372     -0.7024     -0.0214
C(year)[T.2018]             -0.4157     0.1526    -2.7246     0.0064     -0.7147     -0.1167
C(year)[T.2019]             -0.3643     0.1603    -2.2720     0.0231     -0.6785     -0.0500
C(year)[T.2020]             -0.2332     0.1646    -1.4173     0.1564     -0.5558      0.0893
C(year)[T.2021]             -0.2286     0.1708    -1.3388     0.1806     -0.5633      0.1061
C(year)[T.2022]             -0.1500     0.1650    -0.9094     0.3631     -0.4734      0.1733
C(year)[T.2023]             -0.2800     0.1643    -1.7044     0.0883     -0.6020      0.0420
C(year)[T.2024]             -0.3336     0.1633    -2.0433     0.0410     -0.6536     -0.0136
log_yield                    0.1341     0.1420     0.9447     0.3448     -0.1441      0.4124
============================================================================================

Endogenous: log_yield
Instruments: Z_prcp_m1__hinge_neg_q25, Z_prcp_m11__cu, Z_prcp_m12__hinge_pos_q25, Z_prcp_m3__cu, Z_prcp_m5__cu, Z_prcp_m5__sq, Z_prcp_m6__cu, Z_prcp_m6__sq, Z_prcp_m7__hinge_neg_q75, Z_prcp_m8__cu, Z_prcp_m8__sq, Z_temp_m2__cu, Z_temp_m3__cu, Z_temp_m4__cu, Z_temp_m5__cu, Z_temp_m6__cu, Z_temp_m6__sq, Z_temp_m7__cu, Z_temp_m7__sq, Z_temp_m8__cu
Clustered Covariance (One-Way)
Debiased: False
Num Clusters: 42

# Diagnostics Tests

In [126]:
print(iv_res.wooldridge_overid, '\n')

Wooldridge's score test of overidentification
H0: Model is not overidentified.
Statistic: 53.0646
P-value: 0.0000
Distributed: chi2(19)

# Model Overidentified
We need to just identify it and pick the instrument with strongest first stage, reasonable SE and interpretable coefficient

In [127]:
y = "log_area_lead1"
endog = "log_yield"
Z = Z_final

cols = [y, endog] + Z
df = df_iv.set_index(["entity_id","year"])[cols].dropna()

# Manually demeaning to avoid creating dummies
df_dm = demean_2FE(df)
y_dm = df_dm[y]
x_dm = df_dm[endog]

results = []

for z in Z:
    z_dm = df_dm[z]

    r = IV2SLS(y_dm, None, x_dm, z_dm).fit(cov_type="clustered", clusters=df.index.get_level_values("entity_id"))

    fs = r.first_stage
    # Diagnostics for first stage
    diag = fs.diagnostics

    results.append({"Z": z,
                    "beta_log_yield": round(r.params["log_yield"], 3),
                    "se": round(r.std_errors["log_yield"],3),
                    "first_stage_F": round(diag.loc[endog, "f.stat"],3),
                    "first_stage_p": round(diag.loc[endog, "f.pval"],3),
                    "partial_R2": round(diag.loc[endog, "partial.rsquared"],3)})

results_df = pd.DataFrame(results).sort_values("se")
results_df

,Z,beta_log_yield,se,first_stage_F,first_stage_p,partial_R2
15,Z_temp_m6__cu,-0.464,0.341,54.234,0.000,0.026
16,Z_temp_m6__sq,0.314,0.380,16.722,0.000,0.009
17,Z_temp_m7__cu,-0.688,0.462,34.802,0.000,0.013
19,Z_temp_m8__cu,-0.507,0.729,12.542,0.000,0.007
4,Z_prcp_m5__cu,1.591,0.866,15.937,0.000,0.009
14,Z_temp_m5__cu,0.906,0.909,11.363,0.001,0.004
8,Z_prcp_m7__hinge_neg_q75,-2.351,0.963,10.116,0.001,0.006
2,Z_prcp_m12__hinge_pos_q25,1.461,1.057,15.028,0.000,0.003
0,Z_prcp_m1__hinge_neg_q25,1.238,1.204,4.789,0.029,0.003
5,Z_prcp_m5__sq,1.233,1.906,13.528,0.000,0.004
12,Z_temp_m3__cu,-3.269,2.639,1.812,0.178,0.001
18,Z_temp_m7__sq,3.699,3.504,1.550,0.213,0.001
7,Z_prcp_m6__sq,3.819,9.003,0.393,0.531,0.000
13,Z_temp_m4__cu,6.052,11.528,0.301,0.583,0.000
1,Z_prcp_m11__cu,5.692,11.786,0.207,0.649,0.000
6,Z_prcp_m6__cu,10.885,13.679,0.339,0.561,0.000
10,Z_prcp_m8__sq,-10.241,14.338,0.509,0.476,0.000
3,Z_prcp_m3__cu,-4.315,16.708,0.130,0.718,0.000
11,Z_temp_m2__cu,8.802,24.986,0.158,0.691,0.000
9,Z_prcp_m8__cu,-247.173,6726.649,0.001,0.971,0.000

# Running IV with strongest instruments

In [128]:
# Sorting by first stage F
Z_list = results_df.sort_values("first_stage_F", ascending=False)["Z"].head(3).tolist()
y = "log_area_lead1"
endog = "log_yield"

cols = [y, endog, "entity_id", "year"] + Z_list
df0 = df_iv[cols].dropna().copy()

rows = []
for z in Z_list:
    formula = f"{y} ~ 1 + C(entity_id) + C(year) + [{endog} ~ {z}]"
    r = IV2SLS.from_formula(formula, data=df0).fit(
        cov_type="clustered",
        clusters=df0["entity_id"]
    )
    diag = r.first_stage.diagnostics
    rows.append({
        "Z": z,
        "N": int(r.nobs),
        "beta": r.params[endog],
        "se": r.std_errors[endog],
        "F": diag.loc[endog, "f.stat"],
        "pF": diag.loc[endog, "f.pval"],
        "partial_R2": diag.loc[endog, "partial.rsquared"],
    })

df_iv_res = pd.DataFrame(rows).sort_values("F", ascending=False)

df_iv_res

,Z,N,beta,se,F,pF,partial_R2
0,Z_temp_m6__cu,2631,-0.461373,0.319368,54.033286,1.971756e-13,0.026666
1,Z_temp_m7__cu,2631,-0.697058,0.420028,34.674065,3.897900e-09,0.013478
2,Z_temp_m6__sq,2631,0.342706,0.385161,16.419197,5.076845e-05,0.009137

# Testing Exclusion Restriction

In [129]:
def excl_test(df, y, endog, Z, controls=None, fe_entity='entity_id', fe_time='year'):
    if controls is None:
        controls = []
    if isinstance(controls, str):
        controls = [controls]

    fe_part = f'C({fe_entity}) + C({fe_time})'
    base = f"{y}~ 1 + {fe_part} + [{endog} ~ {Z}]"
    stress = base + (" + " + " + ".join(controls) if len(controls) else "")

    cols_needed = [y, endog, Z, fe_entity, fe_time] + controls
    df_use = df.dropna(subset=cols_needed).copy()

    res_base = IV2SLS.from_formula(
    base,
    data=df_use,
    ).fit(cov_type="clustered", clusters=df_use[fe_entity])

    res_stress = IV2SLS.from_formula(
    stress,
    data=df_use,
    ).fit(cov_type="clustered", clusters=df_use[fe_entity])

    comparison = {
    "baseline_beta": res_base.params[endog],
    "baseline_se": res_base.std_errors[endog],
    "stress_beta": res_stress.params[endog],
    "stress_se": res_stress.std_errors[endog],
    }
    print(f"\nExclusion restriction stress test for {Z}")
    print("-" * 38)
    print(f"Baseline:  β = {comparison['baseline_beta']:.3f} "
          f"(SE = {comparison['baseline_se']:.3f})")
    print(f"Stress:    β = {comparison['stress_beta']:.3f} "
          f"(SE = {comparison['stress_se']:.3f})\n")

In [130]:
temp_months = [c for c in df_iv.columns if c.startswith("Z_temp_m")]
prcp_months = [c for c in df_iv.columns if c.startswith("Z_prcp_m")]

def drop_month_family(cols, base):
    return [c for c in cols if not c.startswith(base)]

def controls_temp(m):
    base = f"Z_temp_m{m}"
    other_temp = drop_month_family(temp_months, base)

    near = []
    for k in [m-1, m, m+1]:
        basep = f"Z_prcp_m{k}"
        near += [c for c in prcp_months if c.startswith(basep)]
    return other_temp + near

def controls_prcp(m):
    base = f"Z_prcp_m{m}"
    other_prcp = drop_month_family(prcp_months, base)

    near = []
    for k in [m-1, m, m+1]:
        baset = f"Z_temp_m{k}"
        near += [c for c in temp_months if c.startswith(baset)]
    return other_prcp + near

In [132]:
# Instrument is a temp month 7 cubed
excl_test(df_iv, y="log_area_lead1", endog="log_yield",
          Z="Z_temp_m7__cu",
          controls=controls_temp(7))

# Instrument is a temp month 6 cubed
excl_test(df_iv, y="log_area_lead1", endog="log_yield",
          Z="Z_temp_m6__cu",
          controls=controls_temp(6))

# Instrument is a temp month 6 squared
excl_test(df_iv, y="log_area_lead1", endog="log_yield",
          Z="Z_temp_m6__sq",
          controls=controls_temp(6))

Exclusion restriction stress test for Z_temp_m7__cu
--------------------------------------
Baseline:  β = -0.697 (SE = 0.420)
Stress:    β = -0.276 (SE = 0.382)


Exclusion restriction stress test for Z_temp_m6__cu
--------------------------------------
Baseline:  β = -0.461 (SE = 0.319)
Stress:    β = -0.397 (SE = 0.338)


Exclusion restriction stress test for Z_temp_m6__sq
--------------------------------------
Baseline:  β = 0.343 (SE = 0.385)
Stress:    β = 0.459 (SE = 0.433)

# Final Regression

In [133]:
y = "log_area_lead1"
endog = "log_yield"
z = "Z_temp_m6__cu"

cols = [y, endog, z, "entity_id", "year"]
df_use = df_iv[cols].dropna().copy()

formula = f"{y} ~ 1 + C(entity_id) + C(year) + [{endog} ~ {z}]"
iv_final = IV2SLS.from_formula(formula, data=df_use).fit(
    cov_type="clustered",
    clusters=df_use["entity_id"]
)
print(iv_final.summary)
print(iv_final.first_stage.summary)

                          IV-2SLS Estimation Summary
==============================================================================
Dep. Variable:         log_area_lead1   R-squared:                      0.9402
Estimator:                    IV-2SLS   Adj. R-squared:                 0.9377
No. Observations:                2631   F-statistic:                 1.332e+19
Date:                Mon, Jan 19 2026   P-value (F-stat)                0.0000
Time:                        14:01:59   Distribution:                chi2(105)
Cov. Estimator:             clustered

                                    Parameter Estimates
============================================================================================
                          Parameter  Std. Err.     T-stat    P-value    Lower CI    Upper CI
--------------------------------------------------------------------------------------------
Intercept                    12.887     1.0129     12.723     0.0000      10.902      14.872
C(entity_id)[T.AR_WHEAT]     1.3460     0.0179     75.069     0.0000      1.3108      1.3811
C(entity_id)[T.AZ_WHEAT]     0.1162     0.2308     0.5035     0.6146     -0.3361      0.5685
C(entity_id)[T.CA_WHEAT]     1.5009     0.1579     9.5047     0.0000      1.1914      1.8104
C(entity_id)[T.CO_WHEAT]     2.8205     0.0972     29.023     0.0000      2.6301      3.0110
C(entity_id)[T.DE_WHEAT]    -0.9975     0.0683    -14.612     0.0000     -1.1312     -0.8637
C(entity_id)[T.FL_WHEAT]    -1.8627     0.0459    -40.605     0.0000     -1.9526     -1.7728
C(entity_id)[T.GA_WHEAT]     0.4902     0.0069     70.942     0.0000      0.4766      0.5037
C(entity_id)[T.IA_WHEAT]    -1.1862     0.0137    -86.447     0.0000     -1.2131     -1.1593
C(entity_id)[T.ID_WHEAT]     2.5758     0.1509     17.073     0.0000      2.2801      2.8715
C(entity_id)[T.IL_WHEAT]     2.2775     0.0778     29.259     0.0000      2.1250      2.4301
C(entity_id)[T.IN_WHEAT]     1.7573     0.0921     19.083     0.0000      1.5768      1.9378
C(entity_id)[T.KS_WHEAT]     4.3235     0.0472     91.566     0.0000      4.2309      4.4160
C(entity_id)[T.KY_WHEAT]     1.1211     0.0575     19.493     0.0000      1.0084      1.2338
C(entity_id)[T.LA_WHEAT]    -0.3325     0.0321    -10.362     0.0000     -0.3955     -0.2696
C(entity_id)[T.MD_WHEAT]     0.4082     0.0719     5.6772     0.0000      0.2672      0.5491
C(entity_id)[T.MI_WHEAT]     1.7991     0.0960     18.747     0.0000      1.6110      1.9872
C(entity_id)[T.MN_WHEAT]     2.7250     0.0087     311.50     0.0000      2.7079      2.7421
C(entity_id)[T.MO_WHEAT]     2.1646     0.0300     72.212     0.0000      2.1058      2.2233
C(entity_id)[T.MS_WHEAT]     0.2517     0.0059     42.989     0.0000      0.2402      0.2632
C(entity_id)[T.MT_WHEAT]     3.5837     0.1012     35.417     0.0000      3.3853      3.7820
C(entity_id)[T.NC_WHEAT]     1.2361     0.0162     76.509     0.0000      1.2044      1.2678
C(entity_id)[T.ND_WHEAT]     4.1713     0.0686     60.806     0.0000      4.0368      4.3057
C(entity_id)[T.NE_WHEAT]     2.7411     0.0267     102.73     0.0000      2.6888      2.7934
C(entity_id)[T.NJ_WHEAT]    -1.2638     0.0488    -25.884     0.0000     -1.3595     -1.1681
C(entity_id)[T.NM_WHEAT]     0.3838     0.1442     2.6622     0.0078      0.1012      0.6664
C(entity_id)[T.NV_WHEAT]    -1.8665     0.1978    -9.4383     0.0000     -2.2541     -1.4789
C(entity_id)[T.NY_WHEAT]     0.1988     0.0751     2.6481     0.0081      0.0517      0.3460
C(entity_id)[T.OH_WHEAT]     2.2157     0.0931     23.792     0.0000      2.0332      2.3983
C(entity_id)[T.OK_WHEAT]     3.4578     0.1102     31.366     0.0000      3.2417      3.6739
C(entity_id)[T.OR_WHEAT]     2.1694     0.0796     27.270     0.0000      2.0134      2.3253
C(entity_id)[T.PA_WHEAT]     0.6668     0.0476     14.009     0.0000      0.5735      0.7601
C(entity_id)[T.SC_WHEAT]     0.2546     0.0172     14.822     0.0000      0.2210      0.2883
C(entity_id)[T.SD_WHEAT]     2.9478     0.0845     34.904     0.0000      2.7823      3.1134
C(entity_id)[T.TN_WHEAT]     0.9791     0.0293     33.448     0.0000      0.9217      1.0365
C(entity_id)[T.TX_WHEAT]     3.1008     0.1246     24.895     0.0000      2.8567      3.3449
C(entity_id)[T.UT_WHEAT]     0.3650     0.0187     19.496     0.0000      0.3283      0.4017
C(entity_id)[T.VA_WHEAT]     0.6221     0.0564     11.037     0.0000      0.5116      0.7326
C(entity_id)[T.WA_WHEAT]     3.1595     0.0847     37.296     0.0000      2.9935      3.3255
C(entity_id)[T.WI_WHEAT]     0.1697     0.0754     2.2505     0.0244      0.0219      0.3174
C(entity_id)[T.WV_WHEAT]    -2.5677     0.0361    -71.097     0.0000     -2.6385     -2.4969
C(entity_id)[T.WY_WHEAT]     0.2852     0.1242     2.2957     0.0217      0.0417      0.5286
C(year)[T.1962]              0.1111     0.0242     4.5999     0.0000      0.0638      0.1585
C(year)[T.1963]              0.2481     0.0577     4.2975     0.0000      0.1350      0.3613
C(year)[T.1964]              0.1416     0.0627     2.2597     0.0238      0.0188      0.2645
C(year)[T.1965]              0.1338     0.0633     2.1151     0.0344      0.0098      0.2578
C(year)[T.1966]              0.4818     0.0978     4.9258     0.0000      0.2901      0.6735
C(year)[T.1967]              0.3966     0.0943     4.2062     0.0000      0.2118      0.5814
C(year)[T.1968]              0.1452     0.0785     1.8490     0.0645     -0.0087      0.2991
C(year)[T.1969]              0.1720     0.1156     1.4881     0.1367     -0.0545      0.3985
C(year)[T.1970]              0.2815     0.1377     2.0448     0.0409      0.0117      0.5513
C(year)[T.1971]              0.3202     0.1501     2.1328     0.0329      0.0259      0.6145
C(year)[T.1972]              0.2612     0.1179     2.2159     0.0267      0.0302      0.4923
C(year)[T.1973]              0.5338     0.1158     4.6089     0.0000      0.3068      0.7608
C(year)[T.1974]              0.5813     0.1125     5.1684     0.0000      0.3609      0.8017
C(year)[T.1975]              0.6102     0.1309     4.6604     0.0000      0.3536      0.8668
C(year)[T.1976]              0.5097     0.1216     4.1905     0.0000      0.2713      0.7481
C(year)[T.1977]              0.2330     0.1283     1.8154     0.0695     -0.0186      0.4845
C(year)[T.1978]              0.5120     0.1247     4.1044     0.0000      0.2675      0.7565
C(year)[T.1979]              0.7859     0.1690     4.6502     0.0000      0.4547      1.1172
C(year)[T.1980]              1.0455     0.2016     5.1860     0.0000      0.6504      1.4406
C(year)[T.1981]              1.0510     0.2339     4.4935     0.0000      0.5926      1.5095
C(year)[T.1982]              0.8250     0.2107     3.9154     0.0001      0.4120      1.2380
C(year)[T.1983]              0.9328     0.2187     4.2651     0.0000      0.5042      1.3615
C(year)[T.1984]              0.8201     0.2229     3.6795     0.0002      0.3833      1.2570
C(year)[T.1985]              0.7129     0.1982     3.5970     0.0003      0.3244      1.1013
C(year)[T.1986]              0.5833     0.1849     3.1546     0.0016      0.2209      0.9457
C(year)[T.1987]              0.6997     0.2232     3.1351     0.0017      0.2623      1.1372
C(year)[T.1988]              0.8524     0.2299     3.7073     0.0002      0.4018      1.3031
C(year)[T.1989]              0.8515     0.2030     4.1950     0.0000      0.4537      1.2494
C(year)[T.1990]              0.6435     0.2152     2.9910     0.0028      0.2218      1.0652
C(year)[T.1991]              0.5976     0.1755     3.4052     0.0007      0.2536      0.9415
C(year)[T.1992]              0.6755     0.2277     2.9662     0.0030      0.2291      1.1218
C(year)[T.1993]              0.6528     0.2241     2.9133     0.0036      0.2136      1.0919
C(year)[T.1994]              0.6678     0.2408     2.7735     0.0055      0.1959      1.1397
C(year)[T.1995]              0.7299     0.2334     3.1272     0.0018      0.2724      1.1874
C(year)[T.1996]              0.6956     0.2251     3.0894     0.0020      0.2543      1.1369
C(year)[T.1997]              0.7053     0.2522     2.7964     0.0052      0.2110      1.1996
C(year)[T.1998]              0.6097     0.2409     2.5312     0.0114      0.1376      1.0818
C(year)[T.1999]              0.6237     0.2693     2.3156     0.0206      0.0958      1.1516
C(year)[T.2000]              0.4835     0.2796     1.7293     0.0838     -0.0645      1.0316
C(year)[T.2001]              0.4068     0.2696     1.5086     0.1314     -0.1217      0.9352
C(year)[T.2002]              0.4481     0.2262     1.9812     0.0476      0.0048      0.8914
C(year)[T.2003]              0.4832     0.2463     1.9620     0.0498      0.0005      0.9659
C(year)[T.2004]              0.3351     0.2428     1.3803     0.1675     -0.1407      0.8110
C(year)[T.2005]              0.3343     0.2576     1.2977     0.1944     -0.1706      0.8391
C(year)[T.2006]              0.5481     0.2772     1.9771     0.0480      0.0047      1.0914
C(year)[T.2007]              0.7720     0.2756     2.8006     0.0051      0.2317      1.3122
C(year)[T.2008]              0.5656     0.2938     1.9252     0.0542     -0.0102      1.1415
C(year)[T.2009]              0.2284     0.2577     0.8863     0.3754     -0.2766      0.7334
C(year)[T.2010]              0.5303     0.2858     1.8552     0.0636     -0.0299      1.0905
C(year)[T.2011]              0.5232     0.3047     1.7170     0.0860     -0.0740      1.1205
C(year)[T.2012]              0.6418     0.3107     2.0655     0.0389      0.0328      1.2508
C(year)[T.2013]              0.5102     0.3028     1.6852     0.0920     -0.0832      1.1036
C(year)[T.2014]              0.4474     0.2953     1.5149     0.1298     -0.1314      1.0261
C(year)[T.2015]              0.2897     0.2759     1.0498     0.2938     -0.2512      0.8305
C(year)[T.2016]              0.1361     0.2866     0.4748     0.6349     -0.4256      0.6977
C(year)[T.2017]              0.0912     0.2856     0.3195     0.7494     -0.4685      0.6510
C(year)[T.2018]              0.0251     0.2600     0.0967     0.9229     -0.4844      0.5347
C(year)[T.2019]              0.1038     0.2781     0.3733     0.7089     -0.4413      0.6489
C(year)[T.2020]              0.2163     0.2906     0.7441     0.4568     -0.3534      0.7859
C(year)[T.2021]              0.2277     0.3031     0.7512     0.4525     -0.3663      0.8217
C(year)[T.2022]              0.2904     0.2891     1.0047     0.3150     -0.2761      0.8570
C(year)[T.2023]              0.1990     0.2936     0.6778     0.4979     -0.3765      0.7745
C(year)[T.2024]              0.1499     0.2942     0.5096     0.6103     -0.4267      0.7265
log_yield                   -0.4614     0.3194    -1.4446     0.1486     -1.0873      0.1646
============================================================================================

Endogenous: log_yield
Instruments: Z_temp_m6__cu
Clustered Covariance (One-Way)
Debiased: False
Num Clusters: 42
      First Stage Estimation Results
=========================================
                                log_yield
-----------------------------------------
R-squared                          0.8420
Partial R-squared                  0.0267
Shea's R-squared                   0.0267
Partial F-statistic                54.033
P-value (Partial F-stat)        1.972e-13
Partial F-stat Distn              chi2(1)
========================== ==============
Intercept                          3.2251
                                 (105.63)
C(entity_id)[T.AR_WHEAT]           0.0565
                                 (1287.8)
C(entity_id)[T.AZ_WHEAT]           0.7227
                              (1.006e+05)
C(entity_id)[T.CA_WHEAT]           0.4927
                                 (2129.7)
C(entity_id)[T.CO_WHEAT]          -0.3041
                             (-1.064e+04)
C(entity_id)[T.DE_WHEAT]           0.2115
                                 (54.475)
C(entity_id)[T.FL_WHEAT]          -0.1445
                                (-56.239)
C(entity_id)[T.GA_WHEAT]          -0.0204
                                (-121.04)
C(entity_id)[T.IA_WHEAT]           0.0366
                                 (12.243)
C(entity_id)[T.ID_WHEAT]           0.4778
                                 (653.86)
C(entity_id)[T.IL_WHEAT]           0.2437
                              (3.065e+04)
C(entity_id)[T.IN_WHEAT]           0.2877
                                 (3357.3)
C(entity_id)[T.KS_WHEAT]          -0.1483
                                (-2615.3)
C(entity_id)[T.KY_WHEAT]           0.1789
                                 (1155.1)
C(entity_id)[T.LA_WHEAT]          -0.0932
                                (-31.228)
C(entity_id)[T.MD_WHEAT]           0.2242
                                 (1837.1)
C(entity_id)[T.MI_WHEAT]           0.3011
                                 (3472.0)
C(entity_id)[T.MN_WHEAT]           0.0271
                                 (794.95)
C(entity_id)[T.MO_WHEAT]           0.0934
                                 (1439.4)
C(entity_id)[T.MS_WHEAT]          -0.0181
                                (-640.30)
C(entity_id)[T.MT_WHEAT]          -0.3079
                                (-254.87)
C(entity_id)[T.NC_WHEAT]           0.0507
                                 (3541.5)
C(entity_id)[T.ND_WHEAT]          -0.2063
                                (-179.17)
C(entity_id)[T.NE_WHEAT]          -0.0830
                                (-1150.3)
C(entity_id)[T.NJ_WHEAT]           0.1537
                                 (118.44)
C(entity_id)[T.NM_WHEAT]          -0.4519
                                (-6780.3)
C(entity_id)[T.NV_WHEAT]           0.6210
                                 (208.26)
C(entity_id)[T.NY_WHEAT]           0.2358
                                 (2416.1)
C(entity_id)[T.OH_WHEAT]           0.2902
                                 (1523.1)
C(entity_id)[T.OK_WHEAT]          -0.3439
                                (-2011.3)
C(entity_id)[T.OR_WHEAT]           0.2506
                                 (1238.7)
C(entity_id)[T.PA_WHEAT]           0.1487
                                 (3459.9)
C(entity_id)[T.SC_WHEAT]          -0.0531
                                (-608.08)
C(entity_id)[T.SD_WHEAT]          -0.2635
                                (-1946.3)
C(entity_id)[T.TN_WHEAT]           0.0911
                                 (1181.0)
C(entity_id)[T.TX_WHEAT]          -0.3888
                                (-2370.2)
C(entity_id)[T.UT_WHEAT]          -0.0608
                                (-208.47)
C(entity_id)[T.VA_WHEAT]           0.1758
                                 (1870.8)
C(entity_id)[T.WA_WHEAT]           0.2701
                                 (409.09)
C(entity_id)[T.WI_WHEAT]           0.2362
                              (1.193e+04)
C(entity_id)[T.WV_WHEAT]           0.1107
                                 (37.049)
C(entity_id)[T.WY_WHEAT]          -0.3873
                                (-1726.9)
C(year)[T.1962]                   -0.0111
                                (-0.3627)
C(year)[T.1963]                    0.0262
                                 (0.9284)
C(year)[T.1964]                    0.0587
                                 (2.3219)
C(year)[T.1965]                    0.0536
                                 (1.6363)
C(year)[T.1966]                    0.1421
                                 (5.4625)
C(year)[T.1967]                    0.1413
                                 (4.1742)
C(year)[T.1968]                    0.1413
                                 (4.8388)
C(year)[T.1969]                    0.2085
                                 (6.8794)
C(year)[T.1970]                    0.2596
                                 (10.328)
C(year)[T.1971]                    0.3074
                                 (9.2317)
C(year)[T.1972]                    0.2067
                                 (5.0113)
C(year)[T.1973]                    0.1725
                                 (5.0753)
C(year)[T.1974]                    0.1441
                                 (3.5032)
C(year)[T.1975]                    0.1830
                                 (4.8655)
C(year)[T.1976]                    0.2128
                                 (6.4799)
C(year)[T.1977]                    0.2303
                                 (6.9349)
C(year)[T.1978]                    0.2438
                                 (6.6359)
C(year)[T.1979]                    0.2845
                                 (8.7945)
C(year)[T.1980]                    0.3248
                                 (10.180)
C(year)[T.1981]                    0.3966
                                 (11.393)
C(year)[T.1982]                    0.3638
                                 (10.435)
C(year)[T.1983]                    0.4192
                                 (12.089)
C(year)[T.1984]                    0.4483
                                 (13.082)
C(year)[T.1985]                    0.4182
                                 (9.6983)
C(year)[T.1986]                    0.3647
                                 (8.6053)
C(year)[T.1987]                    0.4721
                                 (13.030)
C(year)[T.1988]                    0.4815
                                 (12.837)
C(year)[T.1989]                    0.3820
                                 (8.8809)
C(year)[T.1990]                    0.4931
                                 (13.995)
C(year)[T.1991]                    0.3568
                                 (6.8831)
C(year)[T.1992]                    0.5593
                                 (15.268)
C(year)[T.1993]                    0.5155
                                 (12.694)
C(year)[T.1994]                    0.5648
                                 (14.904)
C(year)[T.1995]                    0.5326
                                 (12.243)
C(year)[T.1996]                    0.5282
                                 (12.690)
C(year)[T.1997]                    0.6187
                                 (18.831)
C(year)[T.1998]                    0.5940
                                 (18.545)
C(year)[T.1999]                    0.6617
                                 (23.157)
C(year)[T.2000]                    0.6431
                                 (15.999)
C(year)[T.2001]                    0.6040
                                 (16.972)
C(year)[T.2002]                    0.4962
                                 (12.000)
C(year)[T.2003]                    0.5876
                                 (16.260)
C(year)[T.2004]                    0.6268
                                 (15.764)
C(year)[T.2005]                    0.6650
                                 (19.405)
C(year)[T.2006]                    0.6595
                                 (15.496)
C(year)[T.2007]                    0.5976
                                 (14.064)
C(year)[T.2008]                    0.7199
                                 (18.481)
C(year)[T.2009]                    0.6365
                                 (14.396)
C(year)[T.2010]                    0.6571
                                 (16.702)
C(year)[T.2011]                    0.6940
                                 (14.812)
C(year)[T.2012]                    0.7092
                                 (18.941)
C(year)[T.2013]                    0.7286
                                 (17.865)
C(year)[T.2014]                    0.7181
                                 (14.461)
C(year)[T.2015]                    0.7195
                                 (18.234)
C(year)[T.2016]                    0.7587
                                 (17.257)
C(year)[T.2017]                    0.7493
                                 (19.117)
C(year)[T.2018]                    0.7267
                                 (14.314)
C(year)[T.2019]                    0.7734
                                 (21.326)
C(year)[T.2020]                    0.7435
                                 (17.114)
C(year)[T.2021]                    0.7588
                                 (19.172)

# Conclusion
Best instrument is Z_temp_m6__cu
To-do:

report partil f, partial r
second stage estimates

run reduced form

June temperature