In [38]:
import re
import json
import pandas as pd
import numpy as np
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LassoCV
from sklearn.linear_model import Lasso
from linearmodels.panel import PanelOLS
from sklearn.model_selection import KFold
from pathlib import Path

In [5]:
# Generalised demeaning helper function
def demean_2FE(df):
    # Copying dataframe
    df_fe = df.copy()
    # Looping over all columns
    for col in df.columns:
        # Grouping by FE type and and create mean vector
        e_mean = df_fe[col].groupby(level='entity_id').transform('mean')
        t_mean = df_fe[col].groupby(level='year').transform('mean')
        total_mean = df_fe[col].mean()
        # Demeaning
        df_fe[col] = df_fe[col] - e_mean - t_mean + total_mean
    return df_fe

In [40]:
IN = Path("data/processed")

final = json.loads((IN / "final.json").read_text())
df = pd.read_parquet(IN / "bfs_data.parquet")

y = final["y"]
Z = final["Z_selected"]

# Rebuilding multi-index
dfp = df.set_index([final["entity_level"], final["time_level"]]).sort_index()

# Demeaning using helper function
df_dm = demean_2FE(dfp[[y] + Z].dropna())
# Outcome vector
y_dm = df_dm[y]
# Regressor matrix
X_dm = df_dm[Z]

In [50]:
X_nonlinear.reset_index(inplace=True)
X_nonlinear

,entity_id,year,Z_temp_m2,Z_temp_m4,Z_temp_m5,Z_temp_m6,Z_temp_m7,Z_temp_m8,Z_prcp_m1,Z_prcp_m5,...,Z_prcp_m3__hinge_neg_q75,Z_temp_m12__hinge_neg_q25,Z_temp_m12__hinge_neg_q50,Z_temp_m12__hinge_neg_q75,Z_prcp_m10__hinge_neg_q25,Z_prcp_m10__hinge_neg_q50,Z_prcp_m10__hinge_neg_q75,Z_prcp_m7__hinge_neg_q25,Z_prcp_m7__hinge_neg_q50,Z_prcp_m7__hinge_neg_q75
0,AL_WHEAT,1961,0.245117,-0.289144,-0.206328,-1.729577,-0.748486,-1.346183,-1.025532,-1.118673,...,0.000000,0.000000,0.000000,0.000000,0.535107,1.083657,1.676120,0.046498,0.606020,1.250997
1,AL_WHEAT,1962,2.094441,-1.202108,1.088286,0.341506,1.495586,0.614236,1.672448,-1.859408,...,0.618777,0.272698,0.906601,1.554551,0.000000,0.021917,0.614380,0.269897,0.829420,1.474397
2,AL_WHEAT,1963,-1.212727,0.905906,0.640363,-0.019902,-0.930529,0.167278,1.793388,-0.082927,...,1.370706,0.150721,0.784625,1.432575,0.267973,0.816522,1.408986,0.000000,0.000000,0.000000
3,AL_WHEAT,1964,-0.873738,1.058190,-0.231785,1.135239,-1.276316,0.337701,0.436335,-0.290184,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
4,AL_WHEAT,1965,0.002252,1.369677,0.408001,0.311014,0.058665,0.112274,-1.034146,-1.876055,...,0.000000,0.286113,0.920017,1.567967,0.000000,0.000000,0.023488,0.000000,0.000000,0.000000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2668,WY_WHEAT,2021,-0.666428,-0.927003,0.296721,1.965384,2.018413,-0.919929,0.079099,-0.031343,...,0.691214,0.000000,0.504891,1.152842,0.000000,0.186865,0.779328,0.160690,0.720212,1.365190
2669,WY_WHEAT,2022,-0.762352,-1.252326,-1.649876,-0.812292,0.490153,1.091855,0.312901,-0.069682,...,0.549628,0.263084,0.896988,1.544938,0.000000,0.000000,0.232953,0.000000,0.416744,1.061721
2670,WY_WHEAT,2023,-2.568945,-1.790735,1.373101,-0.450066,-0.840964,-0.749394,-0.224052,0.213575,...,0.525758,0.000000,0.473079,1.121029,0.000000,0.000000,0.000000,0.000000,0.068792,0.713769
2671,WY_WHEAT,2024,-0.783939,-0.160934,-2.245822,0.584550,-0.217881,0.386441,-1.116350,-0.539281,...,0.351019,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.429637,1.074614
2672,WY_WHEAT,2025,-0.598637,-1.010986,0.208716,-0.416526,-0.919180,0.366023,0.732364,-1.096057,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.016018,0.000000,0.000000,0.636025

In [51]:
df

,entity_id,year,log_yield,Z_temp_m2,Z_temp_m4,Z_temp_m5,Z_temp_m6,Z_temp_m7,Z_temp_m8,Z_prcp_m1,Z_prcp_m5,Z_prcp_m6,Z_prcp_m8,Z_prcp_m11,Z_prcp_m12,Z_prcp_m3,Z_temp_m12,Z_prcp_m10,Z_prcp_m7
0,AL_WHEAT,1961,3.258097,2.209975,-2.204850,-1.669153,-2.050904,-1.099310,-1.154869,-45.915553,-36.864447,65.777775,16.767785,24.515399,171.686542,63.721351,0.189692,-49.068100,-17.691224
1,AL_WHEAT,1962,3.178054,4.148131,-1.569209,2.647645,-0.348043,0.381419,0.310272,57.177780,-78.811113,21.004442,-48.672215,10.748732,-51.873458,-13.765316,-2.244395,-4.528100,-33.204557
2,AL_WHEAT,1963,3.157000,-3.557254,1.536983,0.547841,-0.287447,-1.151925,-0.282538,37.277780,-19.657780,20.011108,-44.438882,7.828732,-1.071554,-20.485316,-4.995996,-73.218100,12.102109
3,AL_WHEAT,1964,3.218876,-2.979757,1.341887,0.335248,0.651534,-0.891265,-0.738219,24.624447,-35.458732,-40.824130,3.532913,7.195399,8.653208,43.905160,0.993319,54.460471,58.823776
4,AL_WHEAT,1965,3.198673,-0.986176,1.744010,1.152825,-0.953697,-0.711931,-0.597013,-24.110315,-82.873018,60.268727,5.387309,-45.360315,-40.900125,20.190875,-0.019287,0.705233,21.824967
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2668,WY_WHEAT,2021,3.465736,-3.622384,-1.431581,-0.305844,3.481911,2.343117,0.043374,-6.053892,-11.491265,-27.654246,13.848147,-9.902832,3.015919,-4.864541,2.155047,15.503410,-9.154540
2669,WY_WHEAT,2022,2.833213,-1.815428,-2.538534,-1.389492,0.031471,1.612886,1.850630,-3.325320,8.862292,-14.049108,11.761190,2.452784,4.194328,-10.931207,-2.421388,-7.243148,-14.489323
2670,WY_WHEAT,2023,3.401197,-2.957430,-2.322875,2.016526,-0.591113,-0.133623,0.024153,8.952656,-17.437708,54.642197,24.661190,-1.881093,-9.110563,-2.618164,2.120078,23.740564,-1.920844
2671,WY_WHEAT,2024,3.433987,2.365781,0.721691,-1.671981,1.896849,0.533008,0.839526,-3.354541,-4.968538,-28.088445,4.134482,-5.589788,-6.224990,5.623338,3.605474,-5.054891,-13.445844
2672,WY_WHEAT,2025,3.401197,-1.188222,-0.370263,0.330284,0.737552,0.225570,0.343107,-6.159087,-13.427629,-16.045155,-11.022011,-13.704891,-4.671743,3.225936,5.220101,15.190780,0.349808

# Scaling for LASSO

In [8]:
scaler = StandardScaler(with_mean=True, with_std=True)

X_std = scaler.fit_transform(X_dm.values)
dfX_std = pd.DataFrame(X_std, index=X_dm.index, columns=X_dm.columns)

# Checking if standardization worked (mean=0, std=1)
print(dfX_std.describe().loc[["mean","std"]].round().head())

      Z_temp_m2  Z_temp_m4  Z_temp_m5  Z_temp_m6  Z_temp_m7  Z_temp_m8  \
mean       -0.0        0.0       -0.0       -0.0        0.0       -0.0
std         1.0        1.0        1.0        1.0        1.0        1.0

      Z_prcp_m1  Z_prcp_m5  Z_prcp_m6  Z_prcp_m8  Z_prcp_m11  Z_prcp_m12  \
mean       -0.0        0.0       -0.0       -0.0         0.0        -0.0
std         1.0        1.0        1.0        1.0         1.0         1.0

      Z_prcp_m3  Z_temp_m12  Z_prcp_m10  Z_prcp_m7
mean        0.0         0.0         0.0        0.0
std         1.0         1.0         1.0        1.0

# BFS Rule
Depth 0: Default Z
Depth 1: Simple non-linearities

Non-linearity candidates

Squares x^2

Cubics: x^3

Abs: |x|

Hinge splines: max(0, x-c), max(0, c-x)

In [9]:
X_nonlinear = dfX_std.copy()

quantiles = [0.25, 0.5, 0.75]

cols = X_nonlinear.columns
print(len(cols))
for col in cols:
    # Polynomials
    X_nonlinear[f'{col}__sq'] = X_nonlinear[col] ** 2
    X_nonlinear[f'{col}__cu'] = X_nonlinear[col] ** 3
    # Absolute value
    X_nonlinear[f"{col}__abs"] = X_nonlinear[col].abs()

new_cols = {}

for col in cols:
    x = X_nonlinear[col]
    # Iterating over quantiles
    for q in quantiles:
        # Cutting at quantile q
        c = x.quantile(q)
        new_cols[f"{col}__hinge_neg_q{int(q*100)}"] = (c - x).clip(lower=0)

X_nonlinear = pd.concat([X_nonlinear, pd.DataFrame(new_cols, index=X_nonlinear.index)], axis=1)

print(len(X_nonlinear.columns))
print(X_nonlinear.columns)

16
112
Index(['Z_temp_m2', 'Z_temp_m4', 'Z_temp_m5', 'Z_temp_m6', 'Z_temp_m7',
       'Z_temp_m8', 'Z_prcp_m1', 'Z_prcp_m5', 'Z_prcp_m6', 'Z_prcp_m8',
       ...
       'Z_prcp_m3__hinge_neg_q75', 'Z_temp_m12__hinge_neg_q25',
       'Z_temp_m12__hinge_neg_q50', 'Z_temp_m12__hinge_neg_q75',
       'Z_prcp_m10__hinge_neg_q25', 'Z_prcp_m10__hinge_neg_q50',
       'Z_prcp_m10__hinge_neg_q75', 'Z_prcp_m7__hinge_neg_q25',
       'Z_prcp_m7__hinge_neg_q50', 'Z_prcp_m7__hinge_neg_q75'],
      dtype='object', length=112)

# Running LASSO CV

In [10]:
X_vals = X_nonlinear.values
y_vals = y_dm.values

lasso_cv = LassoCV(
    cv=5,
    alphas=100,
    max_iter=20000,
    random_state=0
)

lasso_cv.fit(X_vals, y_vals)

print("Chosen alpha:", lasso_cv.alpha_)
print("Nonzero coefs:", np.sum(lasso_cv.coef_ != 0))

Chosen alpha: 0.00025508448632308406
Nonzero coefs: 73

# Next Step is stability (test over subsamples)

In [15]:
X_all = X_nonlinear.values
y_all = y_dm.values
feature_names = X_nonlinear.columns.to_numpy()

# Extracting alpha chosen by LassoCV
alpha = float(lasso_cv.alpha_)

# Resampling entities
entities = X_nonlinear.index.get_level_values("entity_id").to_numpy()
unique_entities = np.unique(entities)

# No. sample runs
B = 200
# Fraction of entities per run
frac = 0.7
# Seeding
rng = np.random.default_rng(0)

sel_counts = np.zeros(X_all.shape[1], dtype=int)
coef_sums = np.zeros(X_all.shape[1], dtype=float)

for b in range(B):
    # sample entities with replacement, then keep all their rows
    m = int(np.ceil(frac * len(unique_entities)))
    sampled_ents = rng.choice(unique_entities, size=m, replace=True)

    mask = np.isin(entities, sampled_ents)
    X_b = X_all[mask]
    y_b = y_all[mask]

    # Fitting LASSO at fixed alpha
    model = Lasso(alpha=alpha, max_iter=20000, random_state=0)
    model.fit(X_b, y_b)

    nz = model.coef_ != 0
    sel_counts[nz] += 1
    coef_sums[nz] += model.coef_[nz]

# Selection frequencies + mean coef conditional on selection
sel_freq = sel_counts / B
mean_coef = np.zeros_like(coef_sums)
nonzero_mask = sel_counts > 0
mean_coef[nonzero_mask] = coef_sums[nonzero_mask] / sel_counts[nonzero_mask]

stable_cand = (
    pd.DataFrame(
        {
            "feature": feature_names,
            "sel_freq": sel_freq,
            "mean_coef_if_selected": mean_coef,
        }
    )
    .sort_values(["sel_freq", "feature"], ascending=[False, True])
    .reset_index(drop=True)
)

stable_cand.head(30)

                       feature  sel_freq  mean_coef_if_selected
82    Z_prcp_m8__hinge_neg_q25     0.405              -0.007802
83    Z_prcp_m3__hinge_neg_q25     0.400               0.015420
84              Z_prcp_m7__abs     0.390              -0.008652
85                   Z_prcp_m3     0.385               0.005080
86    Z_temp_m2__hinge_neg_q75     0.385               0.015922
87    Z_temp_m5__hinge_neg_q25     0.365              -0.014853
88                  Z_temp_m12     0.360              -0.003152
89    Z_temp_m2__hinge_neg_q25     0.355               0.015366
90    Z_temp_m8__hinge_neg_q25     0.340               0.005760
91    Z_prcp_m7__hinge_neg_q50     0.295               0.013909
92   Z_prcp_m11__hinge_neg_q25     0.270               0.004552
93                   Z_prcp_m1     0.265               0.001657
94    Z_prcp_m6__hinge_neg_q25     0.260              -0.009783
95                  Z_prcp_m10     0.220               0.002134
96    Z_prcp_m8__hinge_neg_q50     0.195              -0.008880
97   Z_temp_m12__hinge_neg_q50     0.195              -0.008245
98    Z_prcp_m3__hinge_neg_q50     0.185               0.023744
99    Z_prcp_m7__hinge_neg_q25     0.165               0.009331
100   Z_temp_m2__hinge_neg_q50     0.155              -0.011080
101   Z_temp_m7__hinge_neg_q50     0.130              -0.000971
102  Z_prcp_m11__hinge_neg_q50     0.125               0.011563
103   Z_temp_m6__hinge_neg_q50     0.060               0.010648
104  Z_prcp_m10__hinge_neg_q50     0.055               0.014534
105   Z_temp_m8__hinge_neg_q50     0.055              -0.005431
106   Z_prcp_m5__hinge_neg_q50     0.050              -0.009429
107   Z_prcp_m6__hinge_neg_q50     0.050               0.003616
108   Z_temp_m4__hinge_neg_q50     0.035              -0.013885
109   Z_prcp_m1__hinge_neg_q50     0.025               0.019684
110   Z_temp_m5__hinge_neg_q50     0.020               0.010819
111  Z_prcp_m12__hinge_neg_q50     0.015              -0.011917

# Deciding threshold for stable set

In [18]:
# Descriptive stats of candidate set
stable_cand.describe()

# Choosing median 0.7
THRESH = 0.7

# Filtering
stable_cand = stable_cand[stable_cand["sel_freq"] > THRESH]

print(stable_cand.shape)

(58, 3)

In [21]:
stable_cand

                      feature  sel_freq  mean_coef_if_selected
0               Z_prcp_m5__cu     1.000              -0.003295
1    Z_prcp_m7__hinge_neg_q75     1.000              -0.059092
2               Z_prcp_m8__cu     1.000              -0.000780
3               Z_temp_m2__cu     1.000              -0.002119
4                   Z_temp_m2     0.995               0.024848
5               Z_temp_m6__cu     0.995              -0.002312
6               Z_temp_m7__cu     0.995              -0.001626
7              Z_prcp_m12__cu     0.990              -0.000482
8               Z_prcp_m1__cu     0.990               0.001273
9               Z_prcp_m1__sq     0.990              -0.011553
10             Z_temp_m12__cu     0.990               0.002112
11             Z_prcp_m11__cu     0.985               0.000606
12              Z_prcp_m3__cu     0.985              -0.000497
13              Z_prcp_m7__sq     0.985               0.012924
14              Z_prcp_m7__cu     0.980              -0.001069
15              Z_temp_m4__cu     0.980              -0.001570
16              Z_prcp_m6__cu     0.975              -0.000594
17              Z_temp_m5__cu     0.975               0.000510
18              Z_temp_m8__cu     0.975              -0.000747
19             Z_prcp_m10__cu     0.970              -0.000012
20   Z_prcp_m1__hinge_neg_q25     0.965               0.066454
21              Z_prcp_m5__sq     0.965               0.012740
22             Z_prcp_m5__abs     0.960              -0.022661
23              Z_prcp_m8__sq     0.960               0.006441
24  Z_prcp_m10__hinge_neg_q25     0.955              -0.038868
25   Z_temp_m6__hinge_neg_q75     0.950               0.024646
26              Z_temp_m6__sq     0.945              -0.007747
27              Z_temp_m4__sq     0.935              -0.006543
28              Z_temp_m7__sq     0.935              -0.005219
29  Z_prcp_m10__hinge_neg_q75     0.925               0.016440
30              Z_prcp_m3__sq     0.925              -0.003861
31                  Z_prcp_m7     0.925              -0.038900
32                 Z_prcp_m11     0.920              -0.010232
33             Z_prcp_m12__sq     0.920               0.006566
34              Z_prcp_m6__sq     0.915               0.004961
35  Z_temp_m12__hinge_neg_q25     0.900               0.042775
36             Z_prcp_m11__sq     0.875               0.003340
37              Z_temp_m2__sq     0.870              -0.002245
38              Z_temp_m5__sq     0.870               0.001149
39   Z_prcp_m1__hinge_neg_q75     0.845              -0.012856
40              Z_temp_m8__sq     0.840               0.003202
41             Z_prcp_m10__sq     0.820              -0.001194
42             Z_prcp_m1__abs     0.810               0.010594
43            Z_temp_m12__abs     0.800              -0.013279
44  Z_prcp_m12__hinge_neg_q25     0.785              -0.036237
45   Z_prcp_m3__hinge_neg_q75     0.785              -0.016602
46             Z_temp_m12__sq     0.785              -0.002115
47  Z_prcp_m12__hinge_neg_q75     0.770               0.015798
48             Z_prcp_m3__abs     0.770               0.014803
49             Z_temp_m8__abs     0.760              -0.007146
50            Z_prcp_m10__abs     0.755               0.008279
51   Z_prcp_m8__hinge_neg_q75     0.750              -0.012987
52   Z_temp_m5__hinge_neg_q75     0.745               0.018367
53   Z_temp_m4__hinge_neg_q75     0.740              -0.022474
54             Z_temp_m7__abs     0.720              -0.009209
55            Z_prcp_m11__abs     0.710              -0.012980
56                 Z_prcp_m12     0.710              -0.013057
57             Z_temp_m4__abs     0.705               0.004204

# Pruning stable set

In [24]:
def feat_name(feat):
    return feat.split("__")[0]

def feat_transformation(feat):
    if '__hinge' in feat: return "hinge"
    if feat.endswith('__cu'): return "cubic"
    if feat.endswith('__abs'): return "abs"
    if feat.endswith('__sq'): return 'square'
    return 'linear'

def hinge_quartile_search(feat):
    search = re.search(r'q(\d+)', feat)
    return int(search.group(1)) if search else None

stable = stable_cand.copy()
stable['feat_name'] = stable['feature'].apply(feat_name)
stable['feat_trans'] = stable['feature'].apply(feat_transformation)
stable['hinge_q'] = stable['feature'].apply(hinge_quartile_search)

In [37]:
# Imposing stricter threshold
pooled = stable[stable["sel_freq"] >= 0.90].copy()

# Grouping by feature name
grouped = pooled.groupby('feat_name')

chosen_vars = []

for name, group in grouped:
    group = group.sort_values('sel_freq', ascending=False)

    # Hinge takes priority
    hinges = group[group['feat_trans'] == "hinge"]
    # Checking if hinges exist
    if len(hinges):
        # Choosing the best hinge
        chosen_vars.append(hinges.iloc[0]['feature'])
        continue

    # Otherwise check for other transformations and prefer linear/sq
    cand = group[group['feat_trans'].isin(['linear','square', 'cubic']).copy()]
    if len(cand):
        chosen = []
        for f in cand['feature']:
            # If 2 were chosen break the loop
            if len(chosen) >= 2: break
            # Avoid selecting both square and cubic
            if f.endswith('__cu') and any(x.endswith('__sq') for x in chosen):
                continue
            chosen.append(f)
        chosen_vars += chosen

Z_new = chosen_vars
print(Z_new, len(Z_new))

['Z_prcp_m1__hinge_neg_q25', 'Z_prcp_m10__hinge_neg_q25', 'Z_prcp_m11__cu', 'Z_prcp_m11', 'Z_prcp_m12__cu', 'Z_prcp_m12__sq', 'Z_prcp_m3__cu', 'Z_prcp_m3__sq', 'Z_prcp_m5__cu', 'Z_prcp_m5__sq', 'Z_prcp_m6__cu', 'Z_prcp_m6__sq', 'Z_prcp_m7__hinge_neg_q75', 'Z_prcp_m8__cu', 'Z_prcp_m8__sq', 'Z_temp_m12__hinge_neg_q25', 'Z_temp_m2__cu', 'Z_temp_m2', 'Z_temp_m4__cu', 'Z_temp_m4__sq', 'Z_temp_m5__cu', 'Z_temp_m6__hinge_neg_q75', 'Z_temp_m7__cu', 'Z_temp_m7__sq', 'Z_temp_m8__cu'] 25

# Running FE on pruned set

In [63]:
# Creating new df with transformations
X = X_nonlinear.copy()
y = df['log_yield'].copy()

# Assert y and X have same index length to concatenate
assert X.index.equals(y.index)

# Concatenating dfs
df_fe = pd.concat([X, y], axis=1)

y = "log_yield"
Z = Z_new

df_fe = df_fe.set_index(["entity_id","year"]).sort_index()
df_fe = df_fe[[y] + Z].dropna()

model = PanelOLS(df_fe[y],
                 df_fe[Z],
                 entity_effects=True,
                 time_effects=True).fit(cov_type='clustered', cluster_entity=True)

print(model.summary)

# joint test that all Z coefficients are zero
formula = [f"{z} = 0" for z in Z]
wald = model.wald_test(formula=formula)
print(wald)

                          PanelOLS Estimation Summary
================================================================================
Dep. Variable:              log_yield   R-squared:                        0.0644
Estimator:                   PanelOLS   R-squared (Between):              0.0077
No. Observations:                2673   R-squared (Within):               0.0194
Date:                Tue, Jan 13 2026   R-squared (Overall):              0.0078
Time:                        10:09:04   Log-likelihood                    1263.0
Cov. Estimator:             Clustered
                                        F-statistic:                      6.9955
Entities:                          42   P-value                           0.0000
Avg Obs:                       63.643   Distribution:                 F(25,2542)
Min Obs:                       51.000
Max Obs:                       65.000   F-statistic (robust):             23.438
                                        P-value                           0.0000
Time periods:                      65   Distribution:                 F(25,2542)
Avg Obs:                       41.123
Min Obs:                       35.000
Max Obs:                       42.000

                                     Parameter Estimates
=============================================================================================
                           Parameter  Std. Err.     T-stat    P-value    Lower CI    Upper CI
---------------------------------------------------------------------------------------------
Z_prcp_m1__hinge_neg_q25      0.0232     0.0112     2.0702     0.0385      0.0012      0.0452
Z_prcp_m10__hinge_neg_q25    -0.0058     0.0086    -0.6744     0.5001     -0.0226      0.0110
Z_prcp_m11__cu                0.0007     0.0005     1.4259     0.1540     -0.0003      0.0017
Z_prcp_m11                   -0.0103     0.0033    -3.1358     0.0017     -0.0168     -0.0039
Z_prcp_m12__cu               -0.0007     0.0003    -2.0212     0.0434     -0.0014  -2.099e-05
Z_prcp_m12__sq                0.0031     0.0024     1.2906     0.1970     -0.0016      0.0078
Z_prcp_m3__cu                -0.0001     0.0008    -0.1276     0.8985     -0.0016      0.0014
Z_prcp_m3__sq                -0.0006     0.0038    -0.1508     0.8802     -0.0081      0.0069
Z_prcp_m5__cu                -0.0033     0.0008    -4.3387     0.0000     -0.0048     -0.0018
Z_prcp_m5__sq                 0.0056     0.0026     2.1111     0.0349      0.0004      0.0108
Z_prcp_m6__cu                -0.0003     0.0006    -0.5815     0.5610     -0.0015      0.0008
Z_prcp_m6__sq                 0.0014     0.0025     0.5704     0.5684     -0.0035      0.0064
Z_prcp_m7__hinge_neg_q75     -0.0087     0.0048    -1.8096     0.0705     -0.0181      0.0007
Z_prcp_m8__cu                -0.0004     0.0003    -1.2176     0.2235     -0.0010      0.0002
Z_prcp_m8__sq                 0.0029     0.0020     1.4186     0.1561     -0.0011      0.0069
Z_temp_m12__hinge_neg_q25     0.0149     0.0093     1.5963     0.1106     -0.0034      0.0331
Z_temp_m2__cu                -0.0023     0.0008    -2.8493     0.0044     -0.0038     -0.0007
Z_temp_m2                     0.0193     0.0043     4.4652     0.0000      0.0108      0.0278
Z_temp_m4__cu                -0.0002     0.0010    -0.1748     0.8613     -0.0021      0.0017
Z_temp_m4__sq                -0.0050     0.0033    -1.5058     0.1323     -0.0114      0.0015
Z_temp_m5__cu                -0.0016     0.0007    -2.4375     0.0149     -0.0030     -0.0003
Z_temp_m6__hinge_neg_q75      0.0222     0.0036     6.1187     0.0000      0.0151      0.0293
Z_temp_m7__cu                -0.0028     0.0006    -4.8722     0.0000     -0.0039     -0.0017
Z_temp_m7__sq                -0.0050     0.0031    -1.6102     0.1075     -0.0112      0.0011
Z_temp_m8__cu                -0.0020     0.0007    -2.6487     0.0081     -0.0034     -0.0005
=============================================================================================

F-test for Poolability: 133.18
P-value: 0.0000
Distribution: F(105,2542)

Included effects: Entity, Time
Linear Equality Hypothesis Test
H0: Linear equality constraint is valid
Statistic: 585.9587
P-value: 0.0000
Distributed: chi2(25)