In [1]:
import pandas as pd
import numpy as np
import json
import src.utils.iv_helpers as iv_h
import src.utils.feature_eng as feat_eng
from src.utils.demeaning import demean_2FE
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LassoCV
from sklearn.linear_model import Lasso
from linearmodels.panel import PanelOLS
from linearmodels.iv import IV2SLS
from sklearn.model_selection import GroupKFold
from pathlib import Path

# Loading Data
We load the panel and construct demeaned outcome and instrument matrix

In [2]:
IN = Path("../data/processed")

final = json.loads((IN / "final.json").read_text())
df = pd.read_parquet(IN / "bfs_data.parquet")

y = final["endog"]
Z = final["Z_selected"]

# Rebuilding multi-index
dfp = df.set_index([final["entity_level"], final["time_level"]]).sort_index()

# Demeaning using helper function
df_dm = demean_2FE(dfp[[y] + Z].dropna())
# Outcome vector
y_dm = df_dm[y]
# Regressor matrix
X_dm = df_dm[Z]

# Scaling for LASSO
Lasso is sensitive to scale so we standardize the instrument columns.

In [3]:
scaler = StandardScaler(with_mean=True, with_std=True)

X_std = scaler.fit_transform(X_dm.values)
dfX_std = pd.DataFrame(X_std, index=X_dm.index, columns=X_dm.columns)

# Checking if standardization worked (mean=0, std=1)
print(dfX_std.describe().loc[["mean","std"]].round().head())

      Z_temp_m2  Z_temp_m4  Z_temp_m5  Z_temp_m6  Z_temp_m7  Z_temp_m8  \
mean       -0.0       -0.0        0.0       -0.0        0.0       -0.0
std         1.0        1.0        1.0        1.0        1.0        1.0

      Z_prcp_m1  Z_prcp_m5  Z_prcp_m6  Z_prcp_m8  Z_prcp_m11  Z_prcp_m12  \
mean       -0.0        0.0        0.0        0.0         0.0        -0.0
std         1.0        1.0        1.0        1.0         1.0         1.0

      Z_prcp_m3  Z_temp_m3
mean        0.0       -0.0
std         1.0        1.0

# Feature Engineering
We will transform the base instruments according to the following rules:

### Polynomials
+ $x = x^2$
+ $x = x^3$

### Absolute Value
+ $x = abs(x)$

### Hinges
+ $x = max[0, x-c_q]$
+ $x = max[0, c_q-x]$

In [4]:
X_temp = dfX_std.copy()

X_nonlinear = feat_eng.build_non_linear_feats(X_temp)

print(len(X_nonlinear.columns))
print(X_nonlinear.columns)

140
Index(['Z_temp_m2', 'Z_temp_m4', 'Z_temp_m5', 'Z_temp_m6', 'Z_temp_m7',
       'Z_temp_m8', 'Z_prcp_m1', 'Z_prcp_m5', 'Z_prcp_m6', 'Z_prcp_m8',
       ...
       'Z_prcp_m3__hinge_pos_q50', 'Z_prcp_m3__hinge_neg_q50',
       'Z_prcp_m3__hinge_pos_q75', 'Z_prcp_m3__hinge_neg_q75',
       'Z_temp_m3__hinge_pos_q25', 'Z_temp_m3__hinge_neg_q25',
       'Z_temp_m3__hinge_pos_q50', 'Z_temp_m3__hinge_neg_q50',
       'Z_temp_m3__hinge_pos_q75', 'Z_temp_m3__hinge_neg_q75'],
      dtype='object', length=140)

# Running LASSO Group K-fold
We choose the LASSO penalty α based on cross-validation that respects panel clustering.

In [5]:
X_vals = X_nonlinear.values
y_vals = y_dm.values

groups = X_nonlinear.index.get_level_values("entity_id").to_numpy()

gkf = GroupKFold(n_splits=5)

lasso_cv = LassoCV(
    cv=gkf.split(X_vals, y_vals, groups=groups),
    alphas=100,
    max_iter=20000,
    random_state=0,
)

lasso_cv.fit(X_vals, y_vals)

print("Chosen alpha:", lasso_cv.alpha_)
print("Nonzero coefs:", np.sum(lasso_cv.coef_ != 0))

Chosen alpha: 0.0002534347355137172
Nonzero coefs: 66

# Testing Over Subsamples For Stability
For robustness, we identify the instruments consistently picked across subsamples.

In [6]:
X_all = X_nonlinear.values
y_all = y_dm.values
feature_names = X_nonlinear.columns.to_numpy()

# Extracting alpha
alpha = float(lasso_cv.alpha_)

# Resampling entities
entities = X_nonlinear.index.get_level_values("entity_id").to_numpy()
unique_entities = np.unique(entities)

# No. sample runs
B = 200
# Fraction of entities per run
frac = 0.7
# Seeding
rng = np.random.default_rng(0)

sel_counts = np.zeros(X_all.shape[1], dtype=int)
coef_sums = np.zeros(X_all.shape[1], dtype=float)

for b in range(B):
    m = int(np.ceil(frac * len(unique_entities)))
    # Random sampling of entities
    sampled_ents = rng.choice(unique_entities, size=m, replace=False)

    mask = np.isin(entities, sampled_ents)
    X_b = X_all[mask]
    y_b = y_all[mask]

    # Fitting LASSO at fixed alpha
    model = Lasso(alpha=alpha, max_iter=20000, random_state=0)
    model.fit(X_b, y_b)

    nz = model.coef_ != 0
    sel_counts[nz] += 1
    coef_sums[nz] += model.coef_[nz]

# Selection frequencies + mean coef conditional on selection
sel_freq = sel_counts / B
mean_coef = np.zeros_like(coef_sums)
nonzero_mask = sel_counts > 0
mean_coef[nonzero_mask] = coef_sums[nonzero_mask] / sel_counts[nonzero_mask]

stable_cand = (
    pd.DataFrame(
        {
            "feature": feature_names,
            "sel_freq": sel_freq,
            "mean_coef_if_selected": mean_coef,
        }
    )
    .sort_values(["sel_freq", "feature"], ascending=[False, True])
    .reset_index(drop=True)
)

stable_cand.head()

                     feature  sel_freq  mean_coef_if_selected
0  Z_prcp_m12__hinge_pos_q25     1.000              -0.017425
1              Z_prcp_m5__cu     1.000              -0.002900
2              Z_temp_m2__cu     1.000              -0.002170
3              Z_temp_m7__cu     1.000              -0.001579
4              Z_temp_m4__cu     0.995              -0.001856

# Imposing Threshold On Stable Set
We keep the features that were picked above a certain threshold.

In [7]:
# Descriptive stats of candidate set
stable_cand.describe()

# Choosing median 0.7
THRESH = 0.7

# Filtering
stable_cand = stable_cand[stable_cand["sel_freq"] > THRESH]

print(stable_cand.shape)

(52, 3)

# Pruning stable set
Since too many variables remain, we prune the instrument set by imposing the following rule:

+ For a base feature, prefer its hinge transformation
+ Otherwise choose up to two of linear, cubic and square - but not square and cubic

In [8]:
stable = stable_cand.copy()
stable['feat_name'] = stable['feature'].apply(iv_h.feat_name)
stable['feat_trans'] = stable['feature'].apply(iv_h.feat_transformation)
stable['hinge_q'] = stable['feature'].apply(iv_h.hinge_quartile_search)

In [9]:
# Imposing stricter threshold
pooled = stable[stable["sel_freq"] >= 0.90].copy()

# Grouping by feature name
grouped = pooled.groupby('feat_name')

chosen_vars = []

for name, group in grouped:
    group = group.sort_values('sel_freq', ascending=False)

    # Hinge takes priority
    hinges = group[group['feat_trans'] == "hinge"]
    # Checking if hinges exist
    if len(hinges):
        # Choosing the best hinge
        chosen_vars.append(hinges.iloc[0]['feature'])
        continue

    # Otherwise check for other transformations and prefer linear/sq
    cand = group[group['feat_trans'].isin(['linear','square', 'cubic'])].copy()
    if len(cand):
        chosen = []
        for f in cand['feature']:
            # If 2 were chosen break the loop
            if len(chosen) >= 2: break
            # Avoid selecting both square and cubic
            if f.endswith('__cu') and any(x.endswith('__sq') for x in chosen):
                continue
            chosen.append(f)
        chosen_vars += chosen

Z_new = chosen_vars
print(Z_new, len(Z_new))

['Z_prcp_m1__hinge_neg_q25', 'Z_prcp_m11__cu', 'Z_prcp_m11__sq', 'Z_prcp_m12__hinge_pos_q25', 'Z_prcp_m3__cu', 'Z_prcp_m3__sq', 'Z_prcp_m5__cu', 'Z_prcp_m5__sq', 'Z_prcp_m6__cu', 'Z_prcp_m6__sq', 'Z_prcp_m8__hinge_neg_q75', 'Z_temp_m2__hinge_pos_q75', 'Z_temp_m3__cu', 'Z_temp_m3__sq', 'Z_temp_m4__hinge_pos_q25', 'Z_temp_m5__cu', 'Z_temp_m6__hinge_neg_q75', 'Z_temp_m7__cu', 'Z_temp_m7__sq', 'Z_temp_m8__cu'] 20

# Running FE on pruned set
We re-run the FE regression on the new pruned set of instruments. We then run a Wald test to verify the instruments have joint significance i.e. they have explanatory power.

In [10]:
# Creating new df with transformations
Z = Z_new
y = 'log_yield'

# Concatenating dfs
df_fe = pd.concat(
    [dfp[[y]], X_nonlinear[Z]],
    axis=1
).dropna()

model = PanelOLS(df_fe[y],
                 df_fe[Z],
                 entity_effects=True,
                 time_effects=True
                 ).fit(cov_type='clustered', cluster_entity=True)


# joint test that all Z coefficients are zero
wald = model.wald_test(formula=[f"{z} = 0" for z in Z])
print(wald)

Linear Equality Hypothesis Test
H0: Linear equality constraint is valid
Statistic: 339.5441
P-value: 0.0000
Distributed: chi2(20)

# Interpretation
We strongly reject null that instruments dont have jointly significant explanatory power at 0.01% confidence level.

# 2SLS
We run a two-stage least squares regression with the new instrument set to estimate its causal effect on area harvested in the following year. We then run an overidentification test.

In [11]:
# Saving list of instruments
Z_final = Z

X_nl = X_nonlinear.copy()

# Aligning index
dfp_aligned = dfp.loc[X_nl.index]

# Creating iv dataframe
df_iv = pd.concat([dfp_aligned, X_nl[Z_final]], axis=1).reset_index()

# Dropping duplicate cols
df_iv = df_iv.loc[:, ~df_iv.columns.duplicated()].copy()

In [12]:
Z = Z_final
endog = 'log_yield'
y = "log_area_lead1"

cols_needed = [y, endog] + Z

df_temp = df_iv.dropna(subset=cols_needed)

formula = f"{y} ~ 1 + [{endog} ~ {' + '.join(Z)}] + C(entity_id) + C(year)"

iv_res = IV2SLS.from_formula(
    formula,
    data=df_temp
).fit(cov_type="clustered", clusters=df_temp["entity_id"])

print(iv_res.summary)

                          IV-2SLS Estimation Summary
==============================================================================
Dep. Variable:         log_area_lead1   R-squared:                      0.9448
Estimator:                    IV-2SLS   Adj. R-squared:                 0.9425
No. Observations:                2631   F-statistic:                  -5.5e+19
Date:                Thu, Jan 22 2026   P-value (F-stat)                1.0000
Time:                        15:37:45   Distribution:                chi2(105)
Cov. Estimator:             clustered

                                    Parameter Estimates
============================================================================================
                          Parameter  Std. Err.     T-stat    P-value    Lower CI    Upper CI
--------------------------------------------------------------------------------------------
Intercept                    11.321     0.6208     18.236     0.0000      10.104      12.537
C(entity_id)[T.AR_WHEAT]     1.3186     0.0106     124.04     0.0000      1.2978      1.3394
C(entity_id)[T.AZ_WHEAT]    -0.2361     0.1368    -1.7257     0.0844     -0.5043      0.0321
C(entity_id)[T.CA_WHEAT]     1.2598     0.0936     13.456     0.0000      1.0763      1.4433
C(entity_id)[T.CO_WHEAT]     2.9689     0.0576     51.525     0.0000      2.8560      3.0818
C(entity_id)[T.DE_WHEAT]    -1.1001     0.0393    -27.970     0.0000     -1.1772     -1.0231
C(entity_id)[T.FL_WHEAT]    -1.7916     0.0290    -61.859     0.0000     -1.8484     -1.7348
C(entity_id)[T.GA_WHEAT]     0.5007     0.0041     122.23     0.0000      0.4927      0.5087
C(entity_id)[T.IA_WHEAT]    -1.2035     0.0103    -117.05     0.0000     -1.2236     -1.1833
C(entity_id)[T.ID_WHEAT]     2.3455     0.0895     26.221     0.0000      2.1702      2.5208
C(entity_id)[T.IL_WHEAT]     2.1587     0.0462     46.775     0.0000      2.0682      2.2491
C(entity_id)[T.IN_WHEAT]     1.6167     0.0546     29.611     0.0000      1.5097      1.7237
C(entity_id)[T.KS_WHEAT]     4.3955     0.0280     157.01     0.0000      4.3407      4.4504
C(entity_id)[T.KY_WHEAT]     1.0333     0.0341     30.302     0.0000      0.9665      1.1001
C(entity_id)[T.LA_WHEAT]    -0.2866     0.0203    -14.114     0.0000     -0.3264     -0.2468
C(entity_id)[T.MD_WHEAT]     0.2984     0.0426     7.0004     0.0000      0.2149      0.3819
C(entity_id)[T.MI_WHEAT]     1.6526     0.0569     29.045     0.0000      1.5411      1.7641
C(entity_id)[T.MN_WHEAT]     2.7116     0.0052     522.81     0.0000      2.7015      2.7218
C(entity_id)[T.MO_WHEAT]     2.1188     0.0178     119.22     0.0000      2.0840      2.1536
C(entity_id)[T.MS_WHEAT]     0.2606     0.0035     75.080     0.0000      0.2538      0.2674
C(entity_id)[T.MT_WHEAT]     3.7381     0.0600     62.309     0.0000      3.6206      3.8557
C(entity_id)[T.NC_WHEAT]     1.2114     0.0096     126.47     0.0000      1.1926      1.2302
C(entity_id)[T.ND_WHEAT]     4.2760     0.0407     105.13     0.0000      4.1963      4.3557
C(entity_id)[T.NE_WHEAT]     2.7818     0.0158     175.84     0.0000      2.7508      2.8129
C(entity_id)[T.NJ_WHEAT]    -1.3386     0.0289    -46.312     0.0000     -1.3953     -1.2820
C(entity_id)[T.NM_WHEAT]     0.6039     0.0855     7.0649     0.0000      0.4364      0.7714
C(entity_id)[T.NV_WHEAT]    -2.1693     0.1172    -18.507     0.0000     -2.3991     -1.9396
C(entity_id)[T.NY_WHEAT]     0.0842     0.0445     1.8915     0.0586     -0.0030      0.1714
C(entity_id)[T.OH_WHEAT]     2.0736     0.0552     37.552     0.0000      1.9653      2.1818
C(entity_id)[T.OK_WHEAT]     3.6261     0.0654     55.477     0.0000      3.4980      3.7542
C(entity_id)[T.OR_WHEAT]     2.0479     0.0472     43.419     0.0000      1.9555      2.1404
C(entity_id)[T.PA_WHEAT]     0.5941     0.0282     21.052     0.0000      0.5388      0.6495
C(entity_id)[T.SC_WHEAT]     0.2809     0.0102     27.575     0.0000      0.2609      0.3008
C(entity_id)[T.SD_WHEAT]     3.0768     0.0501     61.444     0.0000      2.9786      3.1749
C(entity_id)[T.TN_WHEAT]     0.9344     0.0174     53.840     0.0000      0.9004      0.9684
C(entity_id)[T.TX_WHEAT]     3.2909     0.0738     44.564     0.0000      3.1462      3.4357
C(entity_id)[T.UT_WHEAT]     0.3935     0.0111     35.456     0.0000      0.3718      0.4153
C(entity_id)[T.VA_WHEAT]     0.5361     0.0334     16.040     0.0000      0.4706      0.6016
C(entity_id)[T.WA_WHEAT]     3.0302     0.0502     60.329     0.0000      2.9317      3.1286
C(entity_id)[T.WI_WHEAT]     0.0546     0.0447     1.2210     0.2221     -0.0330      0.1422
C(entity_id)[T.WV_WHEAT]    -2.6224     0.0222    -118.26     0.0000     -2.6658     -2.5789
C(entity_id)[T.WY_WHEAT]     0.4748     0.0736     6.4469     0.0000      0.3304      0.6191
C(year)[T.1962]              0.1103     0.0172     6.3983     0.0000      0.0765      0.1441
C(year)[T.1963]              0.2276     0.0521     4.3716     0.0000      0.1255      0.3296
C(year)[T.1964]              0.1060     0.0586     1.8087     0.0705     -0.0089      0.2208
C(year)[T.1965]              0.1004     0.0613     1.6372     0.1016     -0.0198      0.2205
C(year)[T.1966]              0.4061     0.0865     4.6925     0.0000      0.2365      0.5757
C(year)[T.1967]              0.3219     0.0874     3.6852     0.0002      0.1507      0.4931
C(year)[T.1968]              0.0700     0.0723     0.9675     0.3333     -0.0718      0.2118
C(year)[T.1969]              0.0606     0.0933     0.6501     0.5156     -0.1222      0.2435
C(year)[T.1970]              0.1497     0.1099     1.3622     0.1732     -0.0657      0.3652
C(year)[T.1971]              0.1622     0.1160     1.3977     0.1622     -0.0652      0.3895
C(year)[T.1972]              0.1534     0.1004     1.5283     0.1264     -0.0433      0.3501
C(year)[T.1973]              0.4430     0.0930     4.7661     0.0000      0.2608      0.6252
C(year)[T.1974]              0.5105     0.0959     5.3209     0.0000      0.3225      0.6986
C(year)[T.1975]              0.5140     0.1089     4.7217     0.0000      0.3006      0.7273
C(year)[T.1976]              0.4014     0.0984     4.0813     0.0000      0.2087      0.5942
C(year)[T.1977]              0.1136     0.1074     1.0576     0.2902     -0.0969      0.3241
C(year)[T.1978]              0.3869     0.1054     3.6715     0.0002      0.1804      0.5935
C(year)[T.1979]              0.6407     0.1302     4.9196     0.0000      0.3854      0.8959
C(year)[T.1980]              0.8818     0.1577     5.5900     0.0000      0.5726      1.1909
C(year)[T.1981]              0.8497     0.1761     4.8258     0.0000      0.5046      1.1948
C(year)[T.1982]              0.6430     0.1606     4.0045     0.0001      0.3283      0.9578
C(year)[T.1983]              0.7223     0.1605     4.5015     0.0000      0.4078      1.0367
C(year)[T.1984]              0.5943     0.1546     3.8449     0.0001      0.2913      0.8972
C(year)[T.1985]              0.5027     0.1405     3.5789     0.0003      0.2274      0.7780
C(year)[T.1986]              0.3990     0.1395     2.8612     0.0042      0.1257      0.6723
C(year)[T.1987]              0.4625     0.1562     2.9613     0.0031      0.1564      0.7686
C(year)[T.1988]              0.6280     0.1590     3.9487     0.0001      0.3163      0.9398
C(year)[T.1989]              0.6589     0.1510     4.3625     0.0000      0.3629      0.9550
C(year)[T.1990]              0.3981     0.1532     2.5982     0.0094      0.0978      0.6984
C(year)[T.1991]              0.4150     0.1389     2.9876     0.0028      0.1427      0.6872
C(year)[T.1992]              0.4033     0.1588     2.5397     0.0111      0.0921      0.7145
C(year)[T.1993]              0.3941     0.1598     2.4671     0.0136      0.0810      0.7072
C(year)[T.1994]              0.3862     0.1613     2.3944     0.0166      0.0701      0.7023
C(year)[T.1995]              0.4654     0.1589     2.9292     0.0034      0.1540      0.7768
C(year)[T.1996]              0.4318     0.1464     2.9500     0.0032      0.1449      0.7187
C(year)[T.1997]              0.3983     0.1617     2.4628     0.0138      0.0813      0.7153
C(year)[T.1998]              0.3128     0.1570     1.9926     0.0463      0.0051      0.6204
C(year)[T.1999]              0.2954     0.1676     1.7630     0.0779     -0.0330      0.6238
C(year)[T.2000]              0.1635     0.1897     0.8618     0.3888     -0.2084      0.5354
C(year)[T.2001]              0.1064     0.1777     0.5987     0.5494     -0.2418      0.4546
C(year)[T.2002]              0.2003     0.1516     1.3215     0.1863     -0.0968      0.4973
C(year)[T.2003]              0.1927     0.1596     1.2071     0.2274     -0.1202      0.5055
C(year)[T.2004]              0.0230     0.1518     0.1512     0.8798     -0.2745      0.3204
C(year)[T.2005]              0.0044     0.1564     0.0279     0.9777     -0.3023      0.3110
C(year)[T.2006]              0.2208     0.1737     1.2714     0.2036     -0.1196      0.5611
C(year)[T.2007]              0.4739     0.1821     2.6031     0.0092      0.1171      0.8308
C(year)[T.2008]              0.2076     0.1798     1.1541     0.2484     -0.1449      0.5600
C(year)[T.2009]             -0.0886     0.1681    -0.5271     0.5981     -0.4181      0.2409
C(year)[T.2010]              0.2012     0.1798     1.1187     0.2633     -0.1513      0.5537
C(year)[T.2011]              0.1781     0.1899     0.9379     0.3483     -0.1941      0.5502
C(year)[T.2012]              0.2901     0.1957     1.4826     0.1382     -0.0934      0.6737
C(year)[T.2013]              0.1494     0.1934     0.7727     0.4397     -0.2296      0.5285
C(year)[T.2014]              0.0903     0.1900     0.4755     0.6345     -0.2820      0.4627
C(year)[T.2015]             -0.0648     0.1773    -0.3652     0.7150     -0.4124      0.2828
C(year)[T.2016]             -0.2397     0.1787    -1.3414     0.1798     -0.5898      0.1105
C(year)[T.2017]             -0.2798     0.1858    -1.5059     0.1321     -0.6439      0.0844
C(year)[T.2018]             -0.3358     0.1664    -2.0185     0.0435     -0.6618     -0.0097
C(year)[T.2019]             -0.2794     0.1790    -1.5613     0.1185     -0.6302      0.0714
C(year)[T.2020]             -0.1518     0.1840    -0.8249     0.4094     -0.5124      0.2088
C(year)[T.2021]             -0.1459     0.1885    -0.7739     0.4390     -0.5154      0.2236
C(year)[T.2022]             -0.0702     0.1830    -0.3836     0.7013     -0.4289      0.2885
C(year)[T.2023]             -0.1932     0.1802    -1.0723     0.2836     -0.5463      0.1599
C(year)[T.2024]             -0.2460     0.1809    -1.3601     0.1738     -0.6005      0.1085
log_yield                    0.0262     0.1894     0.1383     0.8900     -0.3449      0.3973
============================================================================================

Endogenous: log_yield
Instruments: Z_prcp_m1__hinge_neg_q25, Z_prcp_m11__cu, Z_prcp_m11__sq, Z_prcp_m12__hinge_pos_q25, Z_prcp_m3__cu, Z_prcp_m3__sq, Z_prcp_m5__cu, Z_prcp_m5__sq, Z_prcp_m6__cu, Z_prcp_m6__sq, Z_prcp_m8__hinge_neg_q75, Z_temp_m2__hinge_pos_q75, Z_temp_m3__cu, Z_temp_m3__sq, Z_temp_m4__hinge_pos_q25, Z_temp_m5__cu, Z_temp_m6__hinge_neg_q75, Z_temp_m7__cu, Z_temp_m7__sq, Z_temp_m8__cu
Clustered Covariance (One-Way)
Debiased: False
Num Clusters: 42

# Diagnostics Tests
## Wooldridge Score Test Of Overidentification
We reject the null that the model is not overidentified at 0.0001 confidence level. There is significant evidence that the model is overidentified.

In [13]:
print(iv_res.wooldridge_overid, '\n')

Wooldridge's score test of overidentification
H0: Model is not overidentified.
Statistic: 48.8657
P-value: 0.0002
Distributed: chi2(19)

# Model Overidentified
We need to just identify it and pick the instrument with strongest first stage, reasonable SE and interpretable coefficient.

In [14]:
y = "log_area_lead1"
endog = "log_yield"
Z = Z_final

cols = [y, endog] + Z
df = df_iv.set_index(["entity_id","year"])[cols].dropna()

# Manually demeaning to avoid creating dummies
df_dm = demean_2FE(df)
y_dm = df_dm[y]
x_dm = df_dm[endog]

results = []

for z in Z:
    z_dm = df_dm[z]
    # Fitting each instrument individually
    r = IV2SLS(y_dm, None, x_dm, z_dm).fit(cov_type="clustered", clusters=df.index.get_level_values("entity_id"))

    fs = r.first_stage
    # Diagnostics for first stage
    diag = fs.diagnostics

    # Appending regression results to dictionary
    results.append({"Z": z,
                    "beta_log_yield": round(r.params["log_yield"], 3),
                    "se": round(r.std_errors["log_yield"],3),
                    "first_stage_F": round(diag.loc[endog, "f.stat"],3),
                    "first_stage_p": round(diag.loc[endog, "f.pval"],3),
                    "partial_R2": round(diag.loc[endog, "partial.rsquared"],3)})

# Sorting by standard error
results_df = pd.DataFrame(results).sort_values("se")
results_df.head()

,Z,beta_log_yield,se,first_stage_F,first_stage_p,partial_R2
17,Z_temp_m7__cu,-0.688,0.462,34.802,0.000,0.013
16,Z_temp_m6__hinge_neg_q75,-1.010,0.605,23.330,0.000,0.014
19,Z_temp_m8__cu,-0.507,0.729,12.542,0.000,0.007
6,Z_prcp_m5__cu,1.591,0.866,15.937,0.000,0.009
15,Z_temp_m5__cu,0.906,0.909,11.363,0.001,0.004

# Running IV With Strongest Instruments
We choose the three instruments from our instrument set with the highest F score in the first stage. We then run 2SLS with each of the instruments and record the diagnostics.

In [15]:
# Sorting by first stage F
Z_list = results_df.sort_values("first_stage_F", ascending=False)["Z"].head(3).tolist()
y = "log_area_lead1"
endog = "log_yield"

cols = [y, endog, "entity_id", "year"] + Z_list
df0 = df_iv[cols].dropna().copy()

rows = []
for z in Z_list:
    formula = f"{y} ~ 1 + C(entity_id) + C(year) + [{endog} ~ {z}]"
    r = IV2SLS.from_formula(formula, data=df0).fit(
        cov_type="clustered",
        clusters=df0["entity_id"]
    )
    diag = r.first_stage.diagnostics
    rows.append({
        "Z": z,
        "N": int(r.nobs),
        "beta": r.params[endog],
        "se": r.std_errors[endog],
        "F": diag.loc[endog, "f.stat"],
        "pF": diag.loc[endog, "f.pval"],
        "partial_R2": diag.loc[endog, "partial.rsquared"],
    })

df_iv_res = pd.DataFrame(rows).sort_values("F", ascending=False)

df_iv_res

,Z,N,beta,se,F,pF,partial_R2
0,Z_temp_m7__cu,2631,-0.697058,0.420028,34.674065,3.897900e-09,0.013478
1,Z_temp_m6__hinge_neg_q75,2631,-1.033206,0.556810,23.365087,1.339884e-06,0.014514
2,Z_prcp_m5__cu,2631,1.564490,0.849260,16.335516,5.306014e-05,0.009408

# Testing Exclusion Restriction
We check how sensitive the instruments are by adding nearby weather controls which could capture direct effects e.g. Z_temp_m7__cu gets Z_temp_m8__x. We then re-estimate 2SLS.

In [16]:
temp_months = [c for c in df_iv.columns if c.startswith("Z_temp_m")]
prcp_months = [c for c in df_iv.columns if c.startswith("Z_prcp_m")]

In [17]:
# Instrument is a temp month 7 cubed
iv_h.excl_test(df_iv, y="log_area_lead1", endog="log_yield",
          Z="Z_temp_m7__cu",
          controls=iv_h.controls_temp(7, temp_months=temp_months, prcp_months=prcp_months))

# Instrument is a temp month 6 cubed
iv_h.excl_test(df_iv, y="log_area_lead1", endog="log_yield",
          Z="Z_temp_m6__hinge_neg_q75",
          controls=iv_h.controls_temp(6, temp_months=temp_months, prcp_months=prcp_months))

# Instrument is a temp month 6 squared
iv_h.excl_test(df_iv, y="log_area_lead1", endog="log_yield",
          Z="Z_prcp_m5__cu",
          controls=iv_h.controls_prcp(5, temp_months=temp_months, prcp_months=prcp_months))

Exclusion restriction stress test for Z_temp_m7__cu
--------------------------------------
Baseline:  β = -0.697 (SE = 0.420)
Stress:    β = -0.460 (SE = 0.358)


Exclusion restriction stress test for Z_temp_m6__hinge_neg_q75
--------------------------------------
Baseline:  β = -1.033 (SE = 0.557)
Stress:    β = -0.804 (SE = 0.430)


Exclusion restriction stress test for Z_prcp_m5__cu
--------------------------------------
Baseline:  β = 1.564 (SE = 0.849)
Stress:    β = 1.316 (SE = 0.667)

# Final Regression
Our final 2SLS regression uses the strongest instrument -> $\text{Z\_temp\_m6\_\_hinge\_neg\_q75}$

In [18]:
y = "log_area_lead1"
endog = "log_yield"
z = "Z_temp_m6__hinge_neg_q75"

cols = [y, endog, z, "entity_id", "year"]
df_use = df_iv[cols].dropna().copy()

formula = f"{y} ~ 1 + C(entity_id) + C(year) + [{endog} ~ {z}]"
iv_final = IV2SLS.from_formula(formula, data=df_use).fit(
    cov_type="clustered",
    clusters=df_use["entity_id"]
)

print("beta:", iv_final.params[endog])
print("se:", iv_final.std_errors[endog])
print("p:", iv_final.pvalues[endog])
print(iv_final.first_stage.diagnostics)

beta: -1.0332062231609598
se: 0.5568097319370814
p: 0.06351313384781898
           rsquared  partial.rsquared  shea.rsquared     f.stat    f.pval  \
log_yield  0.840016          0.014514       0.014514  23.365087  0.000001

            f.dist
log_yield  chi2(1)

# Conclusion
## Second Stage
+ $ β = -1.03 $
A 1% increase in the yield of the current year will lead to a 1.03% decrease in the area harvested (or equivalently planted) in the next year, conditional on year and entity (state-level) fixed effects. This is consistent with a supply adjustment.
+ $ p = 0.06 $
It is statistically significant at the 10% level of significance, but not at the 5% level. There is some evidence, but not strong.
## First stage
+ $\text{Partial} R^2 = 0.0145$
+ $p < 0.0001$
+ $\text{F-stat} = 23.37$
The F statistics is 23.37 which exceeds the threshold of 10 for a strong instrument. The partial R squared is small, explaining 1.45% of the variation in X, but is still enough to generate a strong first-stage.

## Economic Interpretation
The instrument captures **extreme negative shocks in June temperature**, which are below the 75 percentile threshold. This helps us isolate the variation which is exogenous to planting decision in the following year, except through it effect on yield in the current year. This holds if we assume that the exclusion restriction holds, that temperature shocks only affect planting decision through current yields.

## Analysis Conclusions
Over a broad set of linear and transformed instruments, June temperature shocks emerged endogenously as the most relevant and credible source of identifying variation. This suggests that information on the yield **mid-season** (6th month) plays the largest overall role on planting decision in the future.